/** 与 migrations/007_rbac.up.js + 014 中 permissions 种子保持一致 */
const ALL_ADMIN_PERMISSION_CODES = [
  'dashboard.view',
  'report.view',
  'report.export',
  'order.view',
  'order.update',
  'order.ship',
  'user.view',
  'user.update',
  'user.points',
  'product.view',
  'product.manage',
  'category.manage',
  'tag.manage',
  'coupon.view',
  'coupon.manage',
  'return.view',
  'return.handle',
  'notification.manage',
  'banner.manage',
  'invite.view',
  'referral.manage',
  'points.manage',
  'shipping.manage',
  'settings.manage',
  'content.manage',
  'audit.view',
  'admin_log.view',
  'role.manage',
  'review.manage',
  'recycle_bin.manage',
];

module.exports = { ALL_ADMIN_PERMISSION_CODES };
