const PROFIT_COLUMNS = [
  'date',
  'month',
  'net_profit_amount',
  'net_margin',
  'paid_amount',
  'product_sales_amount',
  'discount_amount',
  'net_goods_sales_amount',
  'goods_cost_amount',
  'gross_profit_amount',
  'gross_margin',
  'shipping_income',
  'shipping_cost_amount',
  'payment_fee_amount',
  'refund_amount',
  'expense_amount',
  'missing_cost_order_count',
  'missing_cost_item_count',
];

const REPORT_REGISTRY = [
  {
    type: 'sales_daily',
    endpoint: '/admin/reports/sales/daily',
    permission: 'report.view',
    exportPermission: 'report.export',
    serviceHandler: 'getSalesDaily',
    filenamePrefix: 'sales-daily',
    csvColumns: ['date', 'order_count', 'paid_order_count', 'gross_sales', 'net_sales', 'refund_amount', 'discount_amount', 'average_order_value', 'payment_rate', 'refund_rate', 'goods_cost_amount', 'gross_profit_amount', 'gross_margin', 'expense_amount', 'net_profit_amount', 'net_margin', 'missing_cost_order_count', 'missing_cost_item_count'],
  },
  {
    type: 'sales_monthly',
    endpoint: '/admin/reports/sales/monthly',
    permission: 'report.view',
    exportPermission: 'report.export',
    serviceHandler: 'getSalesMonthly',
    filenamePrefix: 'sales-monthly',
    csvColumns: ['month', 'order_count', 'paid_order_count', 'gross_sales', 'net_sales', 'refund_amount', 'discount_amount', 'average_order_value', 'payment_rate', 'refund_rate', 'goods_cost_amount', 'gross_profit_amount', 'gross_margin', 'expense_amount', 'net_profit_amount', 'net_margin'],
  },
  {
    type: 'profit_daily',
    endpoint: '/admin/reports/profit/daily',
    permission: 'report.view',
    exportPermission: 'report.export',
    serviceHandler: 'getProfitDaily',
    filenamePrefix: 'profit-daily',
    csvColumns: PROFIT_COLUMNS.filter((key) => key !== 'month'),
  },
  {
    type: 'profit_monthly',
    endpoint: '/admin/reports/profit/monthly',
    permission: 'report.view',
    exportPermission: 'report.export',
    serviceHandler: 'getProfitMonthly',
    filenamePrefix: 'profit-monthly',
    csvColumns: PROFIT_COLUMNS.filter((key) => key !== 'date'),
  },
  {
    type: 'operating_expenses',
    endpoint: '/admin/expenses',
    permission: 'report.view',
    exportPermission: 'report.export',
    serviceHandler: 'listOperatingExpenses',
    filenamePrefix: 'operating-expenses',
    csvColumns: ['expense_date', 'category', 'amount', 'title', 'remark', 'operator_id', 'created_at', 'updated_at'],
  },
  {
    type: 'product_analysis',
    endpoint: '/admin/reports/products/analysis',
    permission: 'report.view',
    exportPermission: 'report.export',
    serviceHandler: 'getProductsAnalysis',
    filenamePrefix: 'product-analysis',
    csvColumns: ['product_name', 'product_id', 'category_path', 'sales_qty', 'sales_amount', 'order_count', 'buyer_count', 'cost_amount', 'gross_profit', 'gross_margin', 'view_count', 'conversion_rate', 'missing_cost_item_count'],
  },
  {
    type: 'category_analysis',
    endpoint: '/admin/reports/categories/analysis',
    permission: 'report.view',
    exportPermission: 'report.export',
    serviceHandler: 'getCategoriesAnalysis',
    filenamePrefix: 'category-analysis',
    csvColumns: ['category_path', 'product_count', 'active_product_count', 'sales_qty', 'sales_amount', 'order_count', 'buyer_count', 'gross_profit_amount', 'gross_margin', 'stock_qty'],
  },
  {
    type: 'inventory_analysis',
    endpoint: '/admin/reports/inventory/analysis',
    permission: 'report.view',
    exportPermission: 'report.export',
    capability: 'inventoryEnabled',
    serviceHandler: 'getInventoryAnalysis',
    filenamePrefix: 'inventory-analysis',
    csvColumns: ['product_name', 'current_stock', 'warning_stock', 'sales_7d', 'sales_30d', 'avg_daily_sales', 'available_stock_days', 'stock_status'],
  },
  {
    type: 'order_analysis',
    endpoint: '/admin/reports/orders/analysis',
    permission: 'report.view',
    exportPermission: 'report.export',
    serviceHandler: 'getOrdersAnalysis',
    filenamePrefix: 'order-analysis',
    csvColumns: ['date', 'order_count', 'paid_order_count', 'unpaid_order_count', 'cancelled_order_count', 'refund_order_count', 'paid_amount', 'refund_amount', 'average_order_value', 'payment_rate', 'refund_rate'],
  },
  {
    type: 'customer_analysis',
    endpoint: '/admin/reports/customers/analysis',
    permission: 'report.view',
    exportPermission: 'report.export',
    serviceHandler: 'getCustomersAnalysis',
    filenamePrefix: 'customer-analysis',
    csvColumns: ['new_users', 'order_users', 'paying_users', 'repeat_buyer_count', 'repeat_purchase_rate', 'average_order_value', 'average_orders_per_buyer', 'total_paid_amount'],
  },
  {
    type: 'activity_analysis',
    endpoint: '/admin/reports/activities/analysis',
    permission: 'report.view',
    exportPermission: 'report.export',
    serviceHandler: 'getActivitiesAnalysis',
    filenamePrefix: 'activity-analysis',
    csvColumns: ['activity_title', 'activity_type', 'start_at', 'end_at', 'product_count', 'paid_order_count', 'sales_qty', 'sales_amount', 'discount_amount', 'gross_profit_amount', 'view_count', 'conversion_rate'],
    degradedCsvColumns: ['activity_title', 'activity_type', 'start_at', 'end_at', 'product_count'],
  },
  {
    type: 'promotion_conversion',
    endpoint: '/admin/reports/promotions/conversion',
    permission: 'report.view',
    exportPermission: 'report.export',
    serviceHandler: 'getPromotionConversionReport',
    filenamePrefix: 'promotion-conversion',
    csvColumns: ['promotion_title', 'promotion_type', 'promotion_status', 'start_at', 'end_at', 'product_count', 'view_count', 'add_cart_count', 'order_submit_count', 'usage_count', 'confirmed_count', 'released_count', 'paid_order_count', 'sales_amount', 'discount_amount', 'conversion_rate', 'cost_per_paid_order'],
  },
  {
    type: 'coupon_analysis',
    endpoint: '/admin/reports/coupons/analysis',
    permission: 'report.view',
    exportPermission: 'report.export',
    capability: 'couponEnabled',
    serviceHandler: 'getCouponsAnalysis',
    filenamePrefix: 'coupon-analysis',
    csvColumns: ['coupon_campaign_title', 'coupon_campaign_type', 'coupon_title', 'issued_count', 'claimed_count', 'used_count', 'expired_count', 'claim_rate', 'use_rate', 'paid_order_count', 'sales_amount', 'discount_amount', 'net_sales', 'gross_profit_amount', 'roi'],
  },
  {
    type: 'discount_cost',
    endpoint: '/admin/reports/discounts/cost',
    permission: 'report.view',
    exportPermission: 'report.export',
    serviceHandler: 'getDiscountCostReport',
    filenamePrefix: 'discount-cost',
    csvColumns: ['date', 'order_count', 'paid_order_count', 'paid_amount', 'activity_discount_amount', 'coupon_discount_amount', 'points_discount_amount', 'reward_cash_discount_amount', 'shipping_discount_amount', 'total_discount_amount', 'discount_rate'],
  },
  {
    type: 'payment_failure',
    endpoint: '/admin/reports/payments/failures',
    permission: 'report.view',
    exportPermission: 'report.export',
    serviceHandler: 'getPaymentFailureReport',
    filenamePrefix: 'payment-failure',
    csvColumns: ['provider', 'channel_code', 'failure_reason', 'event_type', 'verify_status', 'processing_result', 'risk_level', 'review_status', 'failed_event_count', 'payment_order_count', 'affected_order_count', 'expected_amount', 'actual_amount', 'latest_event_at'],
  },
  {
    type: 'inventory_occupancy',
    endpoint: '/admin/reports/inventory/occupancy',
    permission: 'report.view',
    exportPermission: 'report.export',
    capability: 'inventoryEnabled',
    serviceHandler: 'getInventoryOccupancyReport',
    filenamePrefix: 'inventory-occupancy',
    csvColumns: ['product_name', 'variant_name', 'sku_code', 'stock', 'reserved_stock', 'pending_order_locked_stock', 'pending_order_count', 'locked_stock', 'available_stock', 'warning_stock', 'stock_status'],
  },
  {
    type: 'order_cancel_reason',
    endpoint: '/admin/reports/orders/cancel-reasons',
    permission: 'report.view',
    exportPermission: 'report.export',
    serviceHandler: 'getOrderCancelReasonReport',
    filenamePrefix: 'order-cancel-reasons',
    csvColumns: ['cancel_reason', 'cancel_count', 'user_count', 'cancelled_amount', 'paid_cancelled_amount', 'first_cancelled_at', 'latest_cancelled_at'],
  },
  {
    type: 'search_analysis',
    endpoint: '/admin/reports/search/analysis',
    permission: 'report.view',
    exportPermission: 'report.export',
    serviceHandler: 'getSearchAnalysis',
    filenamePrefix: 'search-analysis',
    csvColumns: ['keyword', 'search_count', 'no_result_count', 'product_click_count', 'order_count', 'sales_amount', 'last_searched_at'],
  },
  {
    type: 'traffic_analysis',
    endpoint: '/admin/reports/traffic',
    permission: 'report.view',
    exportPermission: 'report.export',
    capability: 'trafficAnalyticsEnabled',
    serviceHandler: 'getTrafficAnalysis',
    filenamePrefix: 'traffic-analysis',
    csvColumns: [],
  },
];

const REPORT_REGISTRY_BY_TYPE = Object.fromEntries(REPORT_REGISTRY.map((item) => [item.type, item]));

function getReportDefinition(type) {
  return REPORT_REGISTRY_BY_TYPE[type] || null;
}

function listExportableReports() {
  return REPORT_REGISTRY.filter((item) => item.exportPermission);
}

module.exports = {
  REPORT_REGISTRY,
  REPORT_REGISTRY_BY_TYPE,
  getReportDefinition,
  listExportableReports,
};
