const STARTER_THEME_SKINS = require('../../../../click-send-shop-main/click-send-shop-main/src/constants/starterThemeSkins.data.json');

const byId = new Map(STARTER_THEME_SKINS.map((s) => [s.id, s]));

const VIBRANT_SUNSET_CORAL_SKIN_ID = 'vibrant_sunset_coral';
const HAUTE_BLANC_SKIN_ID = 'haute_blanc';
const GALLERY_MINIMAL_SKIN_ID = 'gallery_minimal';
const OBSIDIAN_BLACK_GOLD_SKIN_ID = 'obsidian_black_gold';
const MIDNIGHT_TITANIUM_SKIN_ID = 'midnight_titanium';
const FESTIVE_RUBY_GOLD_SKIN_ID = 'festive_ruby_gold';
const AETHERIAL_BLANC_SKIN_ID = 'aetherial_blanc';
const ORGANIC_SANDSTONE_SKIN_ID = 'organic_sandstone';

const VIBRANT_SUNSET_CORAL_SKIN = byId.get(VIBRANT_SUNSET_CORAL_SKIN_ID);
const HAUTE_BLANC_SKIN = byId.get(HAUTE_BLANC_SKIN_ID);
const GALLERY_MINIMAL_SKIN = byId.get(GALLERY_MINIMAL_SKIN_ID);
const OBSIDIAN_BLACK_GOLD_SKIN = byId.get(OBSIDIAN_BLACK_GOLD_SKIN_ID);
const MIDNIGHT_TITANIUM_SKIN = byId.get(MIDNIGHT_TITANIUM_SKIN_ID);
const FESTIVE_RUBY_GOLD_SKIN = byId.get(FESTIVE_RUBY_GOLD_SKIN_ID);
const AETHERIAL_BLANC_SKIN = byId.get(AETHERIAL_BLANC_SKIN_ID);
const ORGANIC_SANDSTONE_SKIN = byId.get(ORGANIC_SANDSTONE_SKIN_ID);

module.exports = {
  VIBRANT_SUNSET_CORAL_SKIN_ID,
  VIBRANT_SUNSET_CORAL_SKIN,
  HAUTE_BLANC_SKIN_ID,
  HAUTE_BLANC_SKIN,
  GALLERY_MINIMAL_SKIN_ID,
  GALLERY_MINIMAL_SKIN,
  OBSIDIAN_BLACK_GOLD_SKIN_ID,
  OBSIDIAN_BLACK_GOLD_SKIN,
  MIDNIGHT_TITANIUM_SKIN_ID,
  MIDNIGHT_TITANIUM_SKIN,
  FESTIVE_RUBY_GOLD_SKIN_ID,
  FESTIVE_RUBY_GOLD_SKIN,
  AETHERIAL_BLANC_SKIN_ID,
  AETHERIAL_BLANC_SKIN,
  ORGANIC_SANDSTONE_SKIN_ID,
  ORGANIC_SANDSTONE_SKIN,
  STARTER_THEME_SKINS,
};

