const DEFAULT_SKIN_ID = 'default_life_green';

const DEFAULT_LIFE_GREEN_CONFIG = {
  skinName: '大马通默认生活服务绿',
  bgColor: '#F5F7FA',
  surfaceColor: '#FFFFFF',
  primaryColor: '#00B14F',
  secondaryColor: '#E0F5E9',
  accentColor: '#FFC107',
  priceColor: '#FF5722',
  textColor: '#333333',
  mutedTextColor: '#888888',
  borderColor: '#E5E7EB',
  successColor: '#00A65A',
  warningColor: '#FF9800',
  dangerColor: '#F44336',
  radius: '12px',
  fontFamily: "system-ui, -apple-system, 'PingFang SC', sans-serif",
  shadowStyle: 'soft',
  buttonStyle: 'rounded',
  navStyle: 'floating',
  badgeStyle: 'soft',
  priceStyle: 'bold',
  productCardVariant: 'standard',
  cardStyle: 'elevated',
  cardTextAlign: 'left',
  imageRatio: '1 / 1',
  imageFit: 'cover',
  homeLayout: 'classic',
  headerStyle: 'clean',
  bannerStyle: 'fresh',
  couponStyle: 'ticket',
  memberCardStyle: 'light',
  categoryIconStyle: 'soft',
  motionLevel: 'soft',
  density: 'comfortable',
  adminThemeMode: 'follow_store',
};

/** @deprecated */
const CLASSIC_GOLD_BLACK_CONFIG = DEFAULT_LIFE_GREEN_CONFIG;

const THEME_PRESETS = [
  { id: 'default_life_green', name: '大马通默认生活服务绿', config: DEFAULT_LIFE_GREEN_CONFIG },
  {
    id: 'premium_black_gold',
    name: '高端黑金',
    config: {
      skinName: '高端黑金',
      bgColor: '#121212',
      surfaceColor: '#1E1E1E',
      primaryColor: '#D4AF37',
      secondaryColor: '#2C2C2C',
      accentColor: '#E5C07B',
      priceColor: '#F4D03F',
      textColor: '#F0F0F0',
      mutedTextColor: '#A0A0A0',
      borderColor: '#333333',
      successColor: '#4CAF50',
      warningColor: '#FFB300',
      dangerColor: '#E53935',
      radius: '8px',
      fontFamily: "'Helvetica Neue', 'PingFang SC', serif",
      shadowStyle: 'glow',
      buttonStyle: 'square',
      navStyle: 'glass',
      badgeStyle: 'outline',
      priceStyle: 'luxury',
      productCardVariant: 'premium',
      cardStyle: 'bordered',
      cardTextAlign: 'center',
      imageRatio: '4 / 5',
      imageFit: 'cover',
      homeLayout: 'premium',
      headerStyle: 'dark',
      bannerStyle: 'premium',
      couponStyle: 'premium',
      memberCardStyle: 'blackGold',
      categoryIconStyle: 'outline',
      motionLevel: 'soft',
      density: 'comfortable',
      adminThemeMode: 'follow_store',
    },
  },
  {
    id: 'professional_blue',
    name: '专业蓝白',
    config: {
      skinName: '专业蓝白',
      bgColor: '#F0F2F5',
      surfaceColor: '#FFFFFF',
      primaryColor: '#1890FF',
      secondaryColor: '#E6F7FF',
      accentColor: '#52C41A',
      priceColor: '#E53935',
      textColor: '#1C1E21',
      mutedTextColor: '#8C8C8C',
      borderColor: '#D9D9D9',
      successColor: '#52C41A',
      warningColor: '#FAAD14',
      dangerColor: '#FF4D4F',
      radius: '6px',
      fontFamily: "system-ui, 'PingFang SC', sans-serif",
      shadowStyle: 'subtle',
      buttonStyle: 'rounded',
      navStyle: 'clean',
      badgeStyle: 'solid',
      priceStyle: 'normal',
      productCardVariant: 'standard',
      cardStyle: 'bordered',
      cardTextAlign: 'left',
      imageRatio: '4 / 5',
      imageFit: 'contain',
      homeLayout: 'classic',
      headerStyle: 'clean',
      bannerStyle: 'clean',
      couponStyle: 'minimal',
      memberCardStyle: 'light',
      categoryIconStyle: 'solid',
      motionLevel: 'none',
      density: 'compact',
      adminThemeMode: 'follow_store',
    },
  },
  {
    id: 'promo_red_orange',
    name: '促销红橙',
    config: {
      skinName: '促销红橙',
      bgColor: '#FFF5F5',
      surfaceColor: '#FFFFFF',
      primaryColor: '#FF4500',
      secondaryColor: '#FFEDEB',
      accentColor: '#FFB800',
      priceColor: '#E50012',
      textColor: '#222222',
      mutedTextColor: '#999999',
      borderColor: '#FFDCD7',
      successColor: '#00C853',
      warningColor: '#FF8C00',
      dangerColor: '#D50000',
      radius: '16px',
      fontFamily: "system-ui, 'PingFang SC', sans-serif",
      shadowStyle: 'medium',
      buttonStyle: 'pill',
      navStyle: 'floating',
      badgeStyle: 'solid',
      priceStyle: 'bold',
      productCardVariant: 'deal',
      cardStyle: 'seamless',
      cardTextAlign: 'left',
      imageRatio: '1 / 1',
      imageFit: 'cover',
      homeLayout: 'deal',
      headerStyle: 'premium',
      bannerStyle: 'deal',
      couponStyle: 'deal',
      memberCardStyle: 'gold',
      categoryIconStyle: 'circle',
      motionLevel: 'rich',
      density: 'comfortable',
      adminThemeMode: 'follow_store',
    },
  },
  {
    id: 'fresh_cyan',
    name: '清新蓝绿',
    config: {
      skinName: '清新蓝绿',
      bgColor: '#F4FAFA',
      surfaceColor: '#FFFFFF',
      primaryColor: '#00C4B6',
      secondaryColor: '#E0F7F6',
      accentColor: '#FF7A8A',
      priceColor: '#FF6B6B',
      textColor: '#2D3436',
      mutedTextColor: '#A4B0BE',
      borderColor: '#EDF2F2',
      successColor: '#2ED573',
      warningColor: '#FFA502',
      dangerColor: '#FF4757',
      radius: '18px',
      fontFamily: "system-ui, 'PingFang SC', sans-serif",
      shadowStyle: 'none',
      buttonStyle: 'pill',
      navStyle: 'glass',
      badgeStyle: 'soft',
      priceStyle: 'normal',
      productCardVariant: 'compact',
      cardStyle: 'minimal',
      cardTextAlign: 'left',
      imageRatio: '3 / 4',
      imageFit: 'cover',
      homeLayout: 'magazine',
      headerStyle: 'transparent',
      bannerStyle: 'fresh',
      couponStyle: 'minimal',
      memberCardStyle: 'fresh',
      categoryIconStyle: 'soft',
      motionLevel: 'soft',
      density: 'comfortable',
      adminThemeMode: 'follow_store',
    },
  },
  {
    id: 'minimalist_grey',
    name: '极简灰白',
    config: {
      skinName: '极简灰白',
      bgColor: '#F7F7F8',
      surfaceColor: '#FFFFFF',
      primaryColor: '#111111',
      secondaryColor: '#F0F0F0',
      accentColor: '#444444',
      priceColor: '#D93025',
      textColor: '#1A1A1A',
      mutedTextColor: '#757575',
      borderColor: '#EAEAEA',
      successColor: '#1E8E3E',
      warningColor: '#F9AB00',
      dangerColor: '#D93025',
      radius: '6px',
      fontFamily: "system-ui, 'PingFang SC', sans-serif",
      shadowStyle: 'subtle',
      buttonStyle: 'rounded',
      navStyle: 'clean',
      badgeStyle: 'outline',
      priceStyle: 'normal',
      productCardVariant: 'compact',
      cardStyle: 'bordered',
      cardTextAlign: 'left',
      imageRatio: '1 / 1',
      imageFit: 'cover',
      homeLayout: 'classic',
      headerStyle: 'clean',
      bannerStyle: 'clean',
      couponStyle: 'minimal',
      memberCardStyle: 'light',
      categoryIconStyle: 'outline',
      motionLevel: 'none',
      density: 'compact',
      adminThemeMode: 'follow_store',
    },
  },
];

module.exports = {
  DEFAULT_SKIN_ID,
  DEFAULT_LIFE_GREEN_CONFIG,
  CLASSIC_GOLD_BLACK_CONFIG,
  THEME_PRESETS,
};
