import type { SiteSettings } from "@/types/admin";

export const EMPTY_SITE_SETTINGS: SiteSettings = {
  siteName: "",
  siteDescription: "",
  siteSlogan: "",
  logoUrl: "",
  faviconUrl: "",
  contactPhone: "",
  contactEmail: "",
  contactWhatsApp: "",
  whatsappUrl: "",
  wechatId: "",
  address: "",
  businessHours: "",
  instagramUrl: "",
  facebookUrl: "",
  tiktokUrl: "",
  xhsUrl: "",
  currency: "MYR",
  seoTitle: "",
  seoDescription: "",
  seoKeywords: "",
  ogImageUrl: "",
  googleSiteVerification: "",
  defaultOgImageUrl: "",
  complianceNotice: "",
  ageGateEnabled: "0",
  minimumAge: "18",
  restrictedProductNoindexEnabled: "1",
  footerCompanyName: "",
  footerCopyright: "",
  footerIcpNo: "",
  privacyPolicyPath: "/content/privacy-policy",
  termsPath: "/content/terms-of-service",
  refundPolicyPath: "/content/refund-policy",
  shippingPolicyPath: "/content/shipping-policy",
  supportText: "",
  shippingNotice: "",
  paymentNotice: "",
  autoConfirmReceiveEnabled: "0",
  autoConfirmReceiveDays: "7",
  orderPaymentTimeoutEnabled: "0",
  orderPaymentTimeoutMinutes: "30",
  sstEnabled: "0",
  sstRatePercent: "6",
  sstLabel: "SST",
  sstCustomerNote: "商品价格已含 SST，运费不计税。",
  footerNav: "",
  ga4Enabled: "0",
  ga4MeasurementId: "",
  metaPixelEnabled: "0",
  metaPixelId: "",
};
