import { STOREFRONT_THEME_DEFAULTS } from "@/constants/themeDesignLocks";
import type { ThemeConfig } from "@/types/theme";

export const FIXED_STOREFRONT_DESIGN_ID = "city-goods-fixed";

export const FIXED_STOREFRONT_THEME_CONFIG: ThemeConfig = {
  ...STOREFRONT_THEME_DEFAULTS,
  bgColor: "#F6F7F5",
  surfaceColor: "#FFFFFF",
  primaryColor: "#174735",
  secondaryColor: "#EDF1EE",
  accentColor: "#987331",
  priceColor: "#C24438",
  borderColor: "#DDE2DE",
  textColor: "#171C19",
  mutedTextColor: "#626A65",
  successColor: "#216B4B",
  warningColor: "#987331",
  dangerColor: "#B73C34",
  radius: "8px",
  density: "compact",
  motionLevel: "soft",
  shadowStyle: "subtle",
  buttonStyle: "square",
  navStyle: "clean",
  badgeStyle: "outline",
  priceStyle: "tabularBold",
  productCardVariant: "editorial",
  cardStyle: "minimal",
  cardTextAlign: "left",
  imageRatio: "1 / 1",
  imageFit: "contain",
  homeLayout: "magazine",
  headerStyle: "transparent",
  bannerStyle: "naturalWindow",
  couponStyle: "minimal",
  memberCardStyle: "jadeGold",
  categoryIconStyle: "outline",
  texture: {
    ...STOREFRONT_THEME_DEFAULTS.texture,
    material: "porcelain",
    surface: "matte",
    grain: "none",
    grainOpacity: 0,
    highlight: "none",
    highlightOpacity: 0,
    metal: "none",
    pattern: "none",
    patternOpacity: 0,
    line: "warmHairline",
    shadow: "quietContact",
    temperature: "warmNeutral",
    imageContrast: 0.98,
    imageSaturation: 0.9,
  },
};
