import type { ThemeConfig } from "@/types/theme";

export type AdminAppearanceMode = "light" | "dark";

const LIGHT_ADMIN_APPEARANCE: ThemeConfig = {
  bgColor: "#F5F7FA",
  surfaceColor: "#FFFFFF",
  primaryColor: "#087443",
  secondaryColor: "#E7F2EC",
  accentColor: "#9B7838",
  priceColor: "#C5483F",
  borderColor: "#DFE5E1",
  textColor: "#202823",
  mutedTextColor: "#69736D",
  successColor: "#1F7A4C",
  warningColor: "#A66F22",
  dangerColor: "#C24145",
  radius: "8px",
  fontFamily:
    "system-ui, -apple-system, BlinkMacSystemFont, 'HarmonyOS Sans SC', 'PingFang SC', 'Microsoft YaHei UI', 'Microsoft YaHei', sans-serif",
  shadowStyle: "subtle",
  buttonStyle: "square",
  navStyle: "clean",
  badgeStyle: "outline",
  priceStyle: "tabularBold",
  productCardVariant: "standard",
  cardStyle: "minimal",
  cardTextAlign: "left",
  imageRatio: "1 / 1",
  imageFit: "contain",
  homeLayout: "classic",
  headerStyle: "clean",
  bannerStyle: "clean",
  couponStyle: "minimal",
  memberCardStyle: "light",
  categoryIconStyle: "outline",
  motionLevel: "soft",
  density: "compact",
  texture: {
    material: "adminMatte",
    intensity: "subtle",
    surface: "matte",
    grain: "none",
    grainOpacity: 0,
    highlight: "none",
    highlightOpacity: 0,
    metal: "none",
    pattern: "none",
    patternOpacity: 0,
    line: "neutralHairline",
    shadow: "quietContact",
    temperature: "neutral",
    imageContrast: 1,
    imageSaturation: 1,
  },
};

export const FIXED_ADMIN_APPEARANCE_CONFIGS = {
  light: LIGHT_ADMIN_APPEARANCE,
  dark: {
    ...LIGHT_ADMIN_APPEARANCE,
    bgColor: "#101512",
    surfaceColor: "#181E1A",
    primaryColor: "#63B889",
    secondaryColor: "#26332C",
    accentColor: "#C4A261",
    priceColor: "#E17867",
    borderColor: "#303B35",
    textColor: "#EEF4F0",
    mutedTextColor: "#AAB4AE",
    successColor: "#59B982",
    warningColor: "#D8AA5C",
    dangerColor: "#E06D72",
  },
} satisfies Record<AdminAppearanceMode, ThemeConfig>;
