const REPORT_COLUMN_LABELS = {
  id: '编号',
  date: '日期',
  month: '月份',
  keyword: '关键词',
  category_id: '分类',
  coupon_id: '优惠券',
  coupon_campaign_id: '礼券发行ID',
  coupon_campaign_title: '礼券发行',
  coupon_campaign_type: '礼券发行类型',
  activity_id: '活动',
  order_id: '订单',
  user_id: '用户',
  product_id: '商品',
  order_count: '订单数',
  paid_order_count: '支付订单数',
  cancelled_order_count: '取消订单数',
  refund_order_count: '退款订单数',
  unpaid_order_count: '未支付订单数',
  gross_sales: '销售额',
  product_sales_amount: '商品销售额',
  paid_amount: '实收金额',
  discount_amount: '优惠金额',
  points_discount_amount: '积分抵扣',
  reward_cash_discount_amount: '返现余额抵扣',
  shipping_fee: '运费',
  shipping_income: '用户支付运费',
  shipping_cost_amount: '实际物流成本',
  payment_fee_amount: '支付手续费',
  refund_amount: '退款金额',
  net_sales: '净销售额',
  net_goods_sales_amount: '商品净销售额',
  goods_cost_amount: '商品成本',
  gross_profit: '毛利',
  gross_profit_amount: '商品毛利',
  gross_margin: '毛利率',
  expense_amount: '经营支出',
  net_profit_amount: '净利润',
  net_margin: '净利率',
  missing_cost_order_count: '缺成本订单数',
  missing_cost_item_count: '缺成本商品行数',
  items_sold: '销售件数',
  sales_qty: '销量',
  sales_amount: '销售额',
  discount_allocated: '分摊优惠',
  net_sales_amount: '净销售额',
  cost_amount: '成本金额',
  buyer_count: '购买用户',
  new_users: '新注册用户',
  order_users: '下单用户',
  paying_users: '付费用户',
  active_users: '活跃用户',
  repeat_buyer_count: '复购用户',
  repeat_purchase_rate: '复购率',
  average_orders_per_buyer: '人均订单数',
  total_paid_amount: '付费总额',
  refund_qty: '退款件数',
  current_stock: '当前库存',
  inventory_cost_value: '库存成本',
  view_count: '浏览量',
  add_cart_count: '加购量',
  favorite_count: '收藏量',
  conversion_rate: '转化率',
  average_order_value: '客单价',
  units_per_order: '每单件数',
  payment_rate: '支付率',
  refund_rate: '退款率',
  mom_growth_rate: '环比增长率',
  claim_rate: '领取率',
  use_rate: '使用率',
  roi: '投入产出比',
  pending_orders: '待处理订单',
  product_view_count: '商品浏览次数',
  product_click_count: '商品点击次数',
  add_to_cart_count: '加购次数',
  checkout_start_count: '发起结算次数',
  sales_7d: '近7日销量',
  sales_30d: '近30日销量',
  avg_daily_sales: '日均销量',
  stock_status: '库存状态',
  available_stock_days: '可售天数',
  warning_stock: '预警库存',
  activity_title: '活动名称',
  activity_type: '活动类型',
  promotion_id: '活动ID',
  promotion_title: '活动名称',
  promotion_type: '活动类型',
  promotion_status: '活动状态',
  product_count: '活动商品数',
  order_submit_count: '提交订单数',
  usage_count: '命中次数',
  locked_count: '锁定次数',
  confirmed_count: '确认次数',
  released_count: '释放次数',
  cost_per_paid_order: '单笔支付优惠成本',
  activity_discount_amount: '活动优惠',
  coupon_discount_amount: '优惠券优惠',
  shipping_discount_amount: '运费减免',
  total_discount_amount: '总优惠成本',
  discount_rate: '优惠成本率',
  failure_reason: '失败原因',
  failed_event_count: '失败事件数',
  payment_order_count: '支付单数',
  affected_order_count: '影响订单数',
  expected_amount: '应付金额',
  actual_amount: '实际金额',
  latest_event_at: '最近事件时间',
  risk_level: '风险等级',
  review_status: '复核状态',
  variant_id: 'SKU ID',
  variant_name: 'SKU 名称',
  sku_code: 'SKU 编码',
  stock: '库存',
  reserved_stock: '预留库存',
  pending_order_locked_stock: '待支付占用',
  pending_order_count: '待支付订单数',
  locked_stock: '锁定库存',
  available_stock: '可售库存',
  cancel_reason: '取消原因',
  cancel_count: '取消订单数',
  cancelled_amount: '取消订单金额',
  paid_cancelled_amount: '已支付取消金额',
  first_cancelled_at: '首次取消时间',
  latest_cancelled_at: '最近取消时间',
  活动数: '活动数',
  有销售活动数: '有销售活动数',
  支付订单数: '支付订单数',
  销量: '销量',
  销售额: '销售额',
  优惠金额: '优惠金额',
  优惠成本: '优惠成本',
  商品毛利: '商品毛利',
  浏览量: '浏览量',
  加购量: '加购量',
  提交订单数: '提交订单数',
  活动支付转化率: '活动支付转化率',
  实收金额: '实收金额',
  活动优惠: '活动优惠',
  优惠券优惠: '优惠券优惠',
  积分抵扣: '积分抵扣',
  返现抵扣: '返现抵扣',
  运费减免: '运费减免',
  优惠成本率: '优惠成本率',
  失败事件数: '失败事件数',
  支付单数: '支付单数',
  影响订单数: '影响订单数',
  需复核事件数: '需复核事件数',
  SKU数: 'SKU数',
  锁定库存: '锁定库存',
  预留库存: '预留库存',
  待支付占用: '待支付占用',
  待支付订单数: '待支付订单数',
  缺货SKU: '缺货SKU',
  低库存SKU: '低库存SKU',
  取消订单数: '取消订单数',
  影响用户数: '影响用户数',
  取消订单金额: '取消订单金额',
  已支付取消金额: '已支付取消金额',
  coupon_title: '优惠券名称',
  start_at: '开始时间',
  end_at: '结束时间',
  product_name: '商品名称',
  cover_image: '封面图',
  category_name: '分类',
  category_path: '分类路径',
  parent_category_id: '父分类',
  parent_category_name: '父分类名称',
  last_searched_at: '最后搜索时间',
  created_at: '创建时间',
  updated_at: '更新时间',
  path: '页面路径',
  page_type: '页面类型',
  pv: 'PV',
  uv: 'UV',
  sessions: '会话数',
  unique_ip_count: '独立 IP 数',
  online_visitors: '在线人数',
  new_visitors: '新访客',
  returning_visitors: '回访客',
  avg_duration_seconds: '平均停留秒数',
  bounce_rate: '跳出率',
  exit_count: '退出次数',
  traffic_source: '渠道',
  device: '设备',
  os: '操作系统',
  browser: '浏览器',
  browser_language: '浏览器语言',
  payment_success_count: '支付成功次数',
  status: '状态',
  type: '类型',
  section: '数据分区',
  metric: '指标',
  drop_rate: '流失率',
  product_views: '商品浏览',
  add_to_cart: '加购',
  checkout_start: '发起结算',
  order_submit: '提交订单',
  payment_success: '支付成功',
  provider: '支付网关',
  channel_code: '支付渠道',
  payment_method: '支付方式',
  payment_status: '支付状态',
  order_no: '订单号',
  nickname: '昵称',
  phone: '手机号',
  amount: '金额',
  currency: '币种',
  code: '编码',
  title: '标题',
  value: '数值',
  name: '名称',
  description: '说明',
  reason: '原因',
  remark: '备注',
  notes: '备注',
  total: '合计',
  count: '数量',
  qty: '数量',
  price: '价格',
  cost: '成本',
  fee: '手续费',
  rate: '比率',
  percent: '百分比',
  region: '区域',
  source: '来源',
  module: '模块',
  action: '操作类型',
};

const TOKEN_LABELS = {
  units: '件数', per: '每', order: '订单', rate: '率', sales: '销售', stock: '库存', status: '状态',
  type: '类型', activity: '活动', coupon: '优惠券', product: '商品', category: '分类', user: '用户',
  payment: '支付', refund: '退款', amount: '金额', count: '数量', avg: '平均', daily: '日', monthly: '月',
  mom: '环比', growth: '增长', claim: '领取', use: '使用', paid: '支付', gross: '毛', net: '净',
  items: '件', sold: '售出', warning: '预警', current: '当前', available: '可售', days: '天数',
  view: '浏览', cart: '购物车', favorite: '收藏', profit: '利润', margin: '毛利', conversion: '转化',
};

function humanizeColumnKey(key) {
  if (REPORT_COLUMN_LABELS[key]) return REPORT_COLUMN_LABELS[key];
  if (key.endsWith('_id')) {
    const base = key.slice(0, -3);
    return REPORT_COLUMN_LABELS[base] || `${TOKEN_LABELS[base] || base}编号`;
  }
  const parts = key.split('_').filter(Boolean);
  const labeled = parts.map((part) => TOKEN_LABELS[part] ?? part);
  if (labeled.some((p) => /^[a-z]+$/i.test(String(p)))) return `字段：${key}`;
  return labeled.join('');
}

function labelReportColumn(key) {
  return REPORT_COLUMN_LABELS[key] ?? humanizeColumnKey(key);
}

const STOCK_STATUS_LABELS = {
  low: '低库存',
  low_stock: '低库存',
  normal: '正常',
  out: '缺货',
  out_of_stock: '缺货',
  slow_moving: '滞销',
};
const ACTIVITY_TYPE_LABELS = {
  campaign: '普通活动', coupon: '优惠券活动', flash_sale: '限时秒杀', limited_time_discount: '限时折扣',
  full_reduction: '满减活动', full_discount: '满折活动', member_price: '会员专享', checkin_reward: '签到奖励',
  points_reward: '积分奖励', coupon_activity: '礼券发行', new_user_gift: '新人礼包',
  member_activity: '会员活动', points_bonus: '积分赠送', cashback_activity: '返现活动',
};
const PAYMENT_STATUS_LABELS = { pending: '待支付', unpaid: '未支付', paid: '已支付', success: '支付成功', refunded: '已退款', failed: '支付失败', cancelled: '已取消', partially_refunded: '部分退款' };
const ORDER_STATUS_LABELS = { pending: '待处理', paid: '已支付', processing: '处理中', shipped: '已发货', completed: '已完成', cancelled: '已取消', refunded: '已退款' };
const TRAFFIC_SOURCE_LABELS = { direct: '直接访问', campaign: '广告活动', referral: '外部引荐', organic: '自然搜索', social: '社交媒体', paid: '付费投放' };
const PAGE_TYPE_LABELS = { home: '首页', product: '商品详情', category: '分类页', cart: '购物车', checkout: '结算页', search: '搜索页', other: '其他页面' };
const DEVICE_LABELS = { desktop: '电脑', mobile: '手机', tablet: '平板', unknown: '未知' };

function labelFromMap(map, value, fallback = value) {
  if (value == null || value === '') return '';
  return map[value] ?? fallback;
}

function labelReportCellValue(key, value) {
  if (value === null || value === undefined || value === '') return '';
  if (typeof value === 'boolean') return value ? '是' : '否';
  const s = String(value);
  if (key === 'stock_status') return labelFromMap(STOCK_STATUS_LABELS, s, s);
  if (key === 'activity_type') return labelFromMap(ACTIVITY_TYPE_LABELS, s, s);
  if (key === 'payment_status') return labelFromMap(PAYMENT_STATUS_LABELS, s, s);
  if (key === 'status') return labelFromMap(ORDER_STATUS_LABELS, s, s);
  if (key === 'type' && ACTIVITY_TYPE_LABELS[s]) return labelFromMap(ACTIVITY_TYPE_LABELS, s, s);
  if (key === 'traffic_source') return labelFromMap(TRAFFIC_SOURCE_LABELS, s, s);
  if (key === 'page_type') return labelFromMap(PAGE_TYPE_LABELS, s, s);
  if (key === 'device') return labelFromMap(DEVICE_LABELS, s, s);
  if (key === 'roi' && (value === null || value === undefined || value === '')) return '';
  if (key.endsWith('_rate') && !Number.isNaN(Number(s))) return `${s}%`;
  return s;
}

module.exports = {
  labelReportColumn,
  labelReportCellValue,
  REPORT_COLUMN_LABELS,
};
