/**
 * 报表 CSV 表头中文（与前端 adminDisplayLabels.REPORT_COLUMN_LABELS 保持同步）
 */
const REPORT_COLUMN_LABELS = {
  id: '编号',
  date: '日期',
  month: '月份',
  keyword: '关键词',
  category_id: '分类',
  coupon_id: '优惠券',
  activity_id: '活动',
  order_id: '订单',
  user_id: '用户',
  product_id: '商品',
  order_count: '订单数',
  paid_order_count: '支付订单数',
  cancelled_order_count: '取消订单数',
  refund_order_count: '退款订单数',
  unpaid_order_count: '未支付订单数',
  gross_sales: '销售额',
  discount_amount: '优惠金额',
  shipping_fee: '运费',
  refund_amount: '退款金额',
  net_sales: '净销售额',
  items_sold: '销售件数',
  user_count: '用户数',
  search_count: '搜索次数',
  no_result_count: '无结果次数',
  product_click_count: '商品点击数',
  add_to_cart_count: '加购量',
  issued_count: '发放数量',
  claimed_count: '领取数量',
  used_count: '使用数量',
  expired_count: '过期数量',
  active_users: '活跃用户',
  order_users: '下单用户',
  new_users: '新增用户',
  product_count: '商品数',
  active_product_count: '在售商品数',
  stock_qty: '库存总量',
  warning_stock: '预警库存',
  paying_users: '支付用户数',
  average_order_value: '客单价',
  units_per_order: '每单件数',
  payment_rate: '支付率',
  refund_rate: '退款率',
  mom_growth_rate: '环比增长率',
  claim_rate: '领取率',
  use_rate: '使用率',
  roi: '投入产出比',
  paid_amount: '实收金额',
  pending_orders: '待处理订单',
  product_view_count: '商品浏览次数',
  checkout_start_count: '发起结算次数',
  sales_7d: '近7日销量',
  sales_30d: '近30日销量',
  avg_daily_sales: '日均销量',
  stock_status: '库存状态',
  activity_title: '活动名称',
  activity_type: '活动类型',
  coupon_title: '优惠券名称',
  start_at: '开始时间',
  end_at: '结束时间',
  product_name: '商品名称',
  cover_image: '封面图',
  category_name: '分类',
  sales_qty: '销量',
  sales_amount: '销售额',
  buyer_count: '购买用户',
  refund_qty: '退款件数',
  current_stock: '当前库存',
  view_count: '浏览量',
  add_cart_count: '加购量',
  favorite_count: '收藏量',
  gross_profit: '毛利',
  gross_margin: '毛利率',
  available_stock_days: '可售天数',
  last_searched_at: '最后搜索时间',
  created_at: '创建时间',
  updated_at: '更新时间',
  conversion_rate: '转化率',
  status: '状态',
  type: '类型',
  provider: '支付网关',
  channel_code: '支付渠道',
  payment_method: '支付方式',
  payment_status: '支付状态',
  order_no: '订单号',
  nickname: '昵称',
  phone: '手机号',
  amount: '金额',
  currency: '币种',
  code: '编码',
  title: '标题',
  name: '名称',
  description: '说明',
  reason: '原因',
  remark: '备注',
  notes: '备注',
  total: '合计',
  count: '数量',
  qty: '数量',
  price: '价格',
  cost: '成本',
  fee: '手续费',
  rate: '比率',
  percent: '百分比',
  region: '区域',
  source: '来源',
  module: '模块',
  action: '操作类型',
  event_type: '事件类型',
  verify_status: '验签状态',
  processing_result: '处理结果',
  reconcile_date: '对账日期',
  success_amount: '成功金额',
  diff_amount: '差异金额',
  order_count_recon: '笔数',
};

const TOKEN_LABELS = {
  units: '件数',
  per: '每',
  order: '订单',
  rate: '率',
  sales: '销售',
  stock: '库存',
  status: '状态',
  type: '类型',
  activity: '活动',
  coupon: '优惠券',
  product: '商品',
  category: '分类',
  user: '用户',
  payment: '支付',
  refund: '退款',
  amount: '金额',
  count: '数量',
  avg: '平均',
  daily: '日',
  mom: '环比',
  growth: '增长',
  claim: '领取',
  use: '使用',
};

function humanizeColumnKey(key) {
  if (REPORT_COLUMN_LABELS[key]) return REPORT_COLUMN_LABELS[key];
  if (key.endsWith('_id')) {
    const base = key.slice(0, -3);
    return REPORT_COLUMN_LABELS[base] || `${TOKEN_LABELS[base] || base}编号`;
  }
  const parts = key.split('_').filter(Boolean);
  const labeled = parts.map((part) => TOKEN_LABELS[part] ?? part);
  if (labeled.some((p) => /^[a-z]+$/i.test(p))) return `字段（${key}）`;
  return labeled.join('');
}

function labelReportColumn(key) {
  return REPORT_COLUMN_LABELS[key] ?? humanizeColumnKey(key);
}

module.exports = { labelReportColumn, REPORT_COLUMN_LABELS };
