#!/usr/bin/env python3
"""High-quality Chinese → English for admin UI strings."""
from __future__ import annotations

import re

CJK = re.compile(r"[\u4e00-\u9fff]")

# --- Exact phrase translations (highest priority) ---
PHRASES: dict[str, str] = {
    "管理后台": "Admin Console",
    "请使用管理员账号登录": "Sign in with an administrator account",
    "管理员账号": "Administrator account",
    "输入账号": "Enter account",
    "输入密码": "Enter password",
    "登录中...": "Signing in...",
    "返回前台": "Back to storefront",
    "请输入账号和密码": "Please enter account and password",
    "登录成功": "Signed in successfully",
    "登录失败，请检查账号密码": "Sign-in failed. Check your account and password.",
    "账号设置": "Account settings",
    "退出登录": "Sign out",
    "更换皮肤": "Change theme",
    "切换系统皮肤": "Switch system theme",
    "切换皮肤": "Switch theme",
    "请选择一个皮肤以切换主题样式。": "Pick a theme to update the visual style.",
    "皮肤加载中...": "Loading themes...",
    "搜索菜单...": "Search menu...",
    "关闭菜单": "Close menu",
    "打开菜单": "Open menu",
    "加载失败": "Failed to load",
    "重试": "Retry",
    "全部履约状态": "All fulfillment statuses",
    "全部支付状态": "All payment statuses",
    "未知状态": "Unknown status",
    "未知支付状态": "Unknown payment status",
    "待付款": "Pending payment",
    "已付款": "Paid",
    "已发货": "Shipped",
    "已完成": "Completed",
    "已取消": "Cancelled",
    "退款中": "Refunding",
    "已退款": "Refunded",
    "待支付": "Pending payment",
    "支付失败": "Payment failed",
    "部分退款": "Partially refunded",
    "待审核": "Pending review",
    "已通过": "Approved",
    "已拒绝": "Rejected",
    "处理中": "Processing",
    "待处理": "Pending",
    "已付款(待发货)": "Paid (awaiting shipment)",
    "待发货": "Awaiting shipment",
    "待收货": "Awaiting delivery",
    "全部": "All",
    "成功": "Success",
    "失败": "Failed",
    "大马通": "FlashCast",
    "暂无数据": "No data",
    "暂无商品": "No products",
    "暂无用户": "No users",
    "暂无活动": "No campaigns",
    "暂无内容": "No content",
    "暂无通知": "No notifications",
    "暂无优惠券": "No coupons",
    "保存中...": "Saving...",
    "删除中...": "Deleting...",
    "上传中…": "Uploading…",
    "提交中...": "Submitting...",
    "发布中...": "Publishing...",
    "创建中...": "Creating...",
    "应用中...": "Applying...",
    "新增中...": "Adding...",
    "添加中...": "Adding...",
    "解绑中…": "Unlinking…",
    "进行中": "In progress",
    "进行中活动": "Active campaigns",
    "定时中": "Scheduled",
    "已下单未支付": "Placed, unpaid",
    "手机号和密码必填": "Phone number and password are required",
    "服务器未返回图片地址": "Server did not return an image URL",
    "服务器未返回图片地址，请检查存储配置或稍后重试": "Server did not return an image URL. Check storage settings or try again later.",
    "图片仍在上传中，请等待上传完成后再保存商品。": "Images are still uploading. Wait until upload completes before saving the product.",
    "新用户与未手动选肤用户将默认使用此皮肤。": "New users and users who have not picked a theme will use this skin by default.",
    "标记皮肤适合的业务场景，便于在列表中筛选。": "Tag themes by business scenario to filter them in the list.",
    "主按钮、导航选中、分类选中、后台菜单激活态": "Primary buttons, active nav, selected categories, active admin menu",
    "通用模块（登录 / 未登录均可能展示）": "Common modules (shown for signed-in and guest users)",
    "商品标签样式：实心、柔和底、描边。": "Product tag style: solid, soft background, or outline.",
    "页面动效强度：无动效、柔和、丰富。": "Page motion: none, subtle, or rich.",
    "未配置时回退到打包内置 logo": "Falls back to bundled logo when not configured",
    "未登录首页": "Home (signed out)",
    "登录后首页": "Home (signed in)",
    "仅进入结算": "Checkout only",
    "（不计税）": "(tax excluded)",
    "手机号 *": "Phone number *",
    "如 0": "e.g. 0",
    "如 1.0": "e.g. 1.0",
    "如 🛍️": "e.g. 🛍️",
    "1 星": "1 star",
    "2 星": "2 stars",
    "3 星": "3 stars",
    "4 星": "4 stars",
    "5 星": "5 stars",
    "最近7天": "Last 7 days",
    "最近30天": "Last 30 days",
    "今日销售额": "Today's sales",
    "今日订单": "Today's orders",
    "今日新增": "New today",
    "今日入库": "Inbound today",
    "今日出库": "Outbound today",
    "总商品数": "Total products",
    "总用户数": "Total users",
    "总订单数": "Total orders",
    "总销售额": "Total sales",
    "总管理员": "Total admins",
    "总库存": "Total stock",
    "总订单": "Total orders",
    "流水总数": "Total transactions",
    "缺货SKU": "Out-of-stock SKUs",
    "无订单号": "No order number",
    "无跳转链接": "No link",
    "无匹配记录": "No matching records",
    "无匹配订单": "No matching orders",
    "无商品摘要": "No product summary",
    "无标题": "Untitled",
    "无链接": "No link",
    "未命名分类": "Unnamed category",
    "未命名商品": "Unnamed product",
    "未命名皮肤": "Unnamed theme",
    "未命名优惠券": "Unnamed coupon",
    "未填写电话": "Phone not provided",
    "未填写联系人": "Contact not provided",
    "顺丰速运": "SF Express",
    "小红书": "Xiaohongshu",
    "微信": "WeChat",
    "微信号": "WeChat ID",
    "微信昵称": "WeChat nickname",
    "微信已解绑": "WeChat unlinked",
    "解绑微信": "Unlink WeChat",
    "前台首页": "Storefront home",
    "后台首页": "Admin home",
    "后台管理": "Admin",
    "后台商品表": "Admin product table",
    "好物商城": "Curated mall",
    "签证留学": "Visa & study abroad",
    "生活服务": "Life services",
    "高端服务": "Premium services",
    "促销活动": "Promotions",
    "限时秒杀": "Flash sale",
    "满减活动": "Spend & save",
    "满减券": "Spend & save coupon",
    "折扣券": "Discount coupon",
    "运费券": "Free shipping coupon",
    "新人礼包": "New user bundle",
    "立即领取": "Claim now",
    "去使用": "Use now",
    "设为精选": "Feature",
    "取消精选": "Unfeature",
    "设精选": "Feature",
    "彻底删除": "Delete permanently",
    "恢复失败": "Restore failed",
    "复制失败": "Copy failed",
    "解析失败": "Parse failed",
    "导出失败": "Export failed",
    "导入失败": "Import failed",
    "上传失败": "Upload failed",
    "发布失败": "Publish failed",
    "保存失败": "Save failed",
    "删除失败": "Delete failed",
    "创建失败": "Create failed",
    "更新失败": "Update failed",
    "发送失败": "Send failed",
    "回复失败": "Reply failed",
    "发货失败": "Shipment failed",
    "解绑失败": "Unlink failed",
    "补记失败": "Adjustment failed",
    "重置失败": "Reset failed",
    "操作失败": "Operation failed",
    "添加失败": "Add failed",
    "发布成功": "Published",
    "保存修改": "Save changes",
    "回复成功": "Replied",
    "发货成功": "Shipped",
    "角色已创建": "Role created",
    "角色已更新": "Role updated",
    "内容已更新": "Content updated",
    "活动已发布": "Campaign published",
    "草稿已保存": "Draft saved",
    "密码已重置": "Password reset",
    "状态已更新": "Status updated",
    "库存已更新": "Inventory updated",
    "标签已保存": "Tag saved",
    "图标已上传": "Icon uploaded",
    "图片已上传": "Image uploaded",
    "分类已删除": "Category deleted",
    "分类已隐藏": "Category hidden",
    "已彻底删除": "Permanently deleted",
    "已删除皮肤": "Theme deleted",
    "已关联订单": "Order linked",
    "品牌与视觉": "Brand & visuals",
    "按钮与导航": "Buttons & navigation",
    "预览发布": "Preview & publish",
    "全屏预览": "Fullscreen preview",
    "实时预览": "Live preview",
    "打开日历": "Open calendar",
    "跟随前台": "Match storefront",
    "裁切铺满": "Cover crop",
    "完整显示": "Fit entire image",
    "图片填充": "Image fit",
    "不对比": "No comparison",
    "点击切换": "Tap to switch",
    "当前皮肤": "Current theme",
    "即将开始": "Starting soon",
    "即将支持": "Coming soon",
    "有邀请码": "Has referral code",
    "上级邀请码": "Parent referral code",
    "被邀请人": "Invitee",
    "被邀请人数": "Invitees",
    "邀请人数": "Invites",
    "总邀请记录": "Total referral records",
    "提现/结算": "Withdrawal / settlement",
    "主视觉标题": "Hero title",
    "仅管理员": "Admins only",
    "管理员调整": "Admin adjustment",
    "管理员扣减": "Admin deduction",
    "管理员增加": "Admin credit",
    "管理员拒绝": "Rejected by admin",
    "订单回滚": "Order rollback",
    "订单释放": "Order release",
    "订单扣减": "Order deduction",
    "订单奖励": "Order reward",
    "订单金额": "Order amount",
    "关联订单": "Linked order",
    "订单数据": "Order data",
    "商品数据": "Product data",
    "用户数据": "User data",
    "获奖用户": "Winning users",
    "涉及用户": "Affected users",
    "登录用户": "Signed-in users",
    "全部用户": "All users",
    "普通会员": "Standard member",
    "可用优惠券": "Available coupons",
    "优惠券活动": "Coupon campaign",
    "删除优惠券": "Delete coupon",
    "编辑优惠券": "Edit coupon",
    "新建优惠券": "New coupon",
    "返现记录": "Cashback records",
    "返现规则": "Cashback rules",
    "返现金额": "Cashback amount",
    "积分抵扣": "Points redemption",
    "积分明细": "Points ledger",
    "订单分析": "Order analytics",
    "商品分析": "Product analytics",
    "客户分析": "Customer analytics",
    "分类分析": "Category analytics",
    "活动分析": "Campaign analytics",
    "搜索分析": "Search analytics",
    "库存分析": "Inventory analytics",
    "销售日报": "Daily sales report",
    "销售月报": "Monthly sales report",
    "经营总览": "Business overview",
    "首页运营": "Homepage operations",
    "首页布局": "Home layout",
    "首页运营配置": "Homepage configuration",
    "模块开关": "Module toggles",
    "展示设置": "Display settings",
    "展示规则": "Display rules",
    "适用范围": "Scope",
    "通用规则": "General rules",
    "活动规则": "Campaign rules",
    "积分规则": "Points rules",
    "配送说明": "Delivery notes",
    "配送政策": "Delivery policy",
    "退款政策": "Refund policy",
    "隐私政策": "Privacy policy",
    "用户协议": "Terms of use",
    "关于我们": "About us",
    "帮助中心": "Help center",
    "页脚信息": "Footer",
    "版权信息": "Copyright",
    "品牌信息": "Brand",
    "营业时间": "Business hours",
    "公司地址": "Company address",
    "公司名称": "Company name",
    "站点名称": "Site name",
    "站点描述": "Site description",
    "客服电话": "Support phone",
    "客服邮箱": "Support email",
    "联系方式": "Contact",
    "个人信息": "Profile",
    "修改密码": "Change password",
    "当前密码": "Current password",
    "新密码": "New password",
    "确认密码": "Confirm password",
    "重置密码": "Reset password",
    "最后登录": "Last sign-in",
    "注册时间": "Registered",
    "绑定时间": "Linked at",
    "领取时间": "Claimed at",
    "使用时间": "Used at",
    "创建时间": "Created",
    "更新时间": "Updated",
    "删除时间": "Deleted",
    "通知标题": "Notification title",
    "通知内容": "Notification body",
    "评论内容": "Review text",
    "官方回复": "Official reply",
    "关键词筛选": "Keyword filter",
    "选择类型": "Select type",
    "全部类型": "All types",
    "全部状态": "All statuses",
    "全部星级": "All ratings",
    "请上传图片": "Please upload an image",
    "上传图片": "Upload image",
    "删除此行": "Delete row",
    "手动调整": "Manual adjustment",
    "盘点调整": "Stock count adjustment",
    "累计入账": "Total posted",
    "累计冲正": "Total reversed",
    "累计增加": "Total added",
    "累计消费": "Total spent",
    "变动前": "Before",
    "变动后": "After",
    "单用户": "Per user",
    "本季度": "This quarter",
    "低库存": "Low stock",
    "缺货": "Out of stock",
    "在售": "On sale",
    "达标": "Met threshold",
    "轻微": "Subtle",
    "丰富": "Rich",
    "柔和": "Soft",
    "极简": "Minimal",
    "经典": "Classic",
    "清新": "Fresh",
    "黑金": "Black & gold",
    "金色": "Gold",
    "已启用": "Enabled",
    "已禁用": "Disabled",
    "已保存": "Saved",
    "已创建": "Created",
    "已更新": "Updated",
    "已删除": "Deleted",
    "已关闭": "Closed",
    "已发送": "Sent",
    "已绑定": "Linked",
    "已过期": "Expired",
    "已结束": "Ended",
    "已隐藏": "Hidden",
    "已使用": "Used",
    "已停用": "Deactivated",
    "已入账": "Posted",
    "已冲正": "Reversed",
    "已撤回": "Withdrawn",
    "已提现": "Withdrawn",
    "已精选": "Featured",
    "商品管理": "Products",
    "订单管理": "Orders",
    "用户管理": "Users",
    "支付管理": "Payments",
    "内容管理": "Content",
    "积分管理": "Points",
    "标签管理": "Tags",
    "库存管理": "Inventory",
    "分类管理": "Categories",
    "评论管理": "Reviews",
    "通知管理": "Notifications",
    "活动管理": "Marketing",
    "系统设置": "System settings",
    "站点设置": "Site settings",
    "运费规则": "Shipping rules",
    "角色权限": "Roles & permissions",
    "管理员管理": "Administrators",
    "导出中心": "Export center",
    "数据中心": "Analytics",
    "对账中心": "Reconciliation",
    "渠道配置": "Channel settings",
    "支付流水": "Payment transactions",
    "订单列表": "Order list",
    "用户列表": "User list",
    "领券记录": "Coupon claims",
    "邀请奖励": "Referral rewards",
    "返现管理": "Cashback",
    "优惠券管理": "Coupons",
    "营销活动": "Campaigns",
    "新建活动": "New campaign",
    "编辑活动": "Edit campaign",
    "编辑商品": "Edit product",
    "新增商品": "Add product",
    "删除商品": "Delete product",
    "删除分类": "Delete category",
    "删除活动": "Delete campaign",
    "删除皮肤": "Delete theme",
    "删除标签": "Delete tag",
    "会员等级": "Member tiers",
    "未完成结算": "Abandoned checkouts",
    "Webhook / 事件": "Webhook / events",
    "Banner管理": "Banners",
    "皮肤/视觉设置": "Theme & visuals",
}

# Single-term dictionary (exact match only, no substring replace)
WORDS: dict[str, str] = {
    "下载": "Download",
    "上传": "Upload",
    "不足": "Insufficient",
    "主色": "Primary color",
    "辅色": "Secondary color",
    "促销": "Promotion",
    "保存": "Save",
    "偏低": "Low",
    "停用": "Deactivate",
    "入库": "Inbound",
    "出库": "Outbound",
    "全国": "Nationwide",
    "全部": "All",
    "关闭": "Close",
    "其他": "Other",
    "分类": "Category",
    "切换": "Switch",
    "删除": "Delete",
    "刷新": "Refresh",
    "加粗": "Bold",
    "动效": "Motion",
    "包邮": "Free shipping",
    "匿名": "Anonymous",
    "发光": "Glow",
    "发布": "Publish",
    "变动": "Change",
    "可选": "Optional",
    "名称": "Name",
    "启用": "Enable",
    "售价": "Sale price",
    "商品": "Product",
    "回复": "Reply",
    "固定": "Fixed",
    "圆形": "Circle",
    "圆角": "Rounded",
    "地址": "Address",
    "增加": "Increase",
    "备注": "Notes",
    "复制": "Copy",
    "失败": "Failed",
    "好物": "Curated picks",
    "姓名": "Name",
    "实心": "Solid",
    "客服": "Support",
    "密度": "Density",
    "层级": "Layer",
    "居中": "Center",
    "展开": "Expand",
    "收起": "Collapse",
    "履约": "Fulfillment",
    "已读": "Read",
    "常规": "Normal",
    "平板": "Tablet",
    "库存": "Inventory",
    "开启": "Enable",
    "待审": "Pending review",
    "恢复": "Restore",
    "悬浮": "Elevated",
    "成功": "Success",
    "手机": "Mobile",
    "扣减": "Deduct",
    "拒绝": "Reject",
    "排序": "Sort",
    "推荐": "Recommended",
    "描边": "Outline",
    "操作": "Actions",
    "支付": "Payment",
    "数量": "Quantity",
    "新品": "New arrivals",
    "新增": "Add",
    "方角": "Square",
    "无缝": "Seamless",
    "时间": "Time",
    "星级": "Rating",
    "昨日": "Yesterday",
    "今日": "Today",
    "显示": "Show",
    "更多": "More",
    "未知": "Unknown",
    "未读": "Unread",
    "本月": "This month",
    "上月": "Last month",
    "杂志": "Magazine",
    "标准": "Standard",
    "标签": "Tag",
    "标记": "Mark",
    "桌面": "Desktop",
    "正常": "Normal",
    "比例": "Ratio",
    "浅色": "Light",
    "深色": "Dark",
    "添加": "Add",
    "满减": "Spend & save",
    "热销": "Hot sale",
    "热门": "Popular",
    "状态": "Status",
    "玻璃": "Glass",
    "生活": "Life",
    "用户": "User",
    "电话": "Phone",
    "登录": "Sign in",
    "禁用": "Disable",
    "秒杀": "Flash sale",
    "积分": "Points",
    "符号": "Symbol",
    "答案": "Answer",
    "签证": "Visa",
    "简洁": "Clean",
    "类型": "Type",
    "系统": "System",
    "紧凑": "Compact",
    "编辑": "Edit",
    "访客": "Guest",
    "说明": "Description",
    "账号": "Account",
    "货币": "Currency",
    "选择": "Select",
    "透明": "Transparent",
    "通知": "Notification",
    "通过": "Approve",
    "金额": "Amount",
    "问题": "Question",
    "阴影": "Shadow",
    "隐藏": "Hide",
    "首页": "Home",
    "高级": "Premium",
    "默认": "Default",
    "仪表盘": "Dashboard",
    "优惠券": "Coupon",
    "会员卡": "Membership card",
    "内容": "Content",
    "订单": "Order",
    "购物车": "Cart",
    "输入框": "Input",
    "销售额": "Sales",
    "邀请": "Invite",
    "奖励": "Reward",
    "返现": "Cashback",
    "领券": "Coupon claim",
    "记录": "Records",
    "营销": "Marketing",
    "运营": "Operations",
    "运费": "Shipping",
    "规则": "Rules",
    "设置": "Settings",
    "站点": "Site",
    "皮肤": "Theme",
    "视觉": "Visual",
    "审计": "Audit",
    "日志": "Logs",
    "角色": "Role",
    "权限": "Permissions",
    "管理员": "Administrator",
    "回收站": "Recycle bin",
    "导出": "Export",
    "导入": "Import",
    "中心": "Center",
    "数据": "Data",
    "报表": "Report",
    "分析": "Analytics",
    "总览": "Overview",
    "日报": "Daily report",
    "月报": "Monthly report",
    "客户": "Customer",
    "搜索": "Search",
    "评论": "Review",
    "售后": "After-sales",
    "渠道": "Channel",
    "配置": "Settings",
    "流水": "Transactions",
    "对账": "Reconciliation",
    "未完成": "Incomplete",
    "结算": "Checkout",
    "列表": "List",
    "新建": "Create",
    "详情": "Details",
    "描述": "Description",
    "价格": "Price",
    "筛选": "Filter",
    "暂无": "No data",
    "返回": "Back",
    "打开": "Open",
    "永久": "Permanent",
    "清空": "Clear",
    "预览": "Preview",
    "草稿": "Draft",
    "必填": "Required",
    "邮箱": "Email",
    "会员": "Member",
    "等级": "Tier",
    "管理": "Management",
    "后台": "Admin",
    "前台": "Storefront",
    "一级": "Level 1",
    "二级": "Level 2",
    "三级": "Level 3",
    "业务": "Business",
    "模块": "Module",
    "组件": "Component",
    "组件库": "Component library",
    "按钮": "Button",
    "导航": "Navigation",
    "头部": "Header",
    "底部": "Footer",
    "页面": "Page",
    "布局": "Layout",
    "风格": "Style",
    "样式": "Style",
    "颜色": "Color",
    "背景": "Background",
    "卡片": "Card",
    "图标": "Icon",
    "图片": "Image",
    "链接": "Link",
    "标题": "Title",
    "文案": "Copy",
    "模板": "Template",
    "字段": "Field",
    "规格": "Variant",
    "摘要": "Summary",
    "合计": "Subtotal",
    "奖励": "Reward",
    "冲正": "Reversal",
    "入账": "Posted",
    "提现": "Withdrawal",
    "精选": "Featured",
    "草稿": "Draft",
    "对比": "Compare",
    "对齐": "Alignment",
    "左对齐": "Align left",
    "居中": "Center",
    "中等": "Medium",
    "家庭装": "Family pack",
    "标准装": "Standard pack",
    "主导航": "Main navigation",
    "主按钮": "Primary button",
    "次按钮": "Secondary button",
    "危险色": "Danger color",
    "成功色": "Success color",
    "警告色": "Warning color",
    "强调色": "Accent color",
    "正文色": "Body text color",
    "次文字色": "Secondary text color",
    "边框色": "Border color",
    "价格色": "Price color",
    "状态颜色": "Status colors",
    "基础颜色": "Base colors",
    "基础信息": "Basic info",
    "危险按钮": "Danger button",
    "成功按钮": "Success button",
    "禁用按钮": "Disabled button",
    "移动端": "Mobile",
    "自定义": "Custom",
    "联系人": "Contact",
    "社交媒体": "Social",
    "税种": "Tax type",
    "盘点": "Stock count",
    "关键词": "Keyword",
    "筛选": "Filter",
    "确认": "Confirm",
    "提交": "Submit",
    "取消": "Cancel",
    "加载": "Load",
    "重试": "Retry",
    "解绑": "Unlink",
    "绑定": "Link",
    "补记": "Adjustment",
    "重置": "Reset",
    "隐藏": "Hide",
    "显示": "Show",
    "应用": "Apply",
    "定时": "Scheduled",
    "入账": "Post",
    "撤回": "Withdraw",
    "过期": "Expired",
    "结束": "Ended",
    "开始": "Started",
    "发送": "Send",
    "接收": "Receive",
    "填写": "Enter",
    "命名": "Name",
    "手动": "Manual",
    "自动": "Auto",
    "全国": "Nationwide",
    "上架": "List product",
    "下架": "Delist",
    "美食": "Food",
    "舒适": "Comfortable",
    "商品卡": "Product card",
    "券样式": "Coupon style",
    "分类页": "Category page",
    "内容页": "Content page",
    "手机号": "Phone number",
    "邀请码": "Referral code",
    "订单号": "Order number",
    "邀请人": "Referrer",
    "文字": "Text",
    "对齐": "Alignment",
    "文字对齐": "Text alignment",
    "设为默认": "Set as default",
    "收货地址": "Shipping address",
    "我的页面": "My account",
    "设为草稿": "Save as draft",
    "活动总览": "Campaign overview",
    "我的订单": "My orders",
    "每日签到": "Daily check-in",
    "支付方式": "Payment method",
    "匹配用户数": "Matched users",
    "待处理订单": "Pending orders",
    "密码已修改": "Password updated",
    "页脚": "Footer",
    "页脚与内容": "Footer & content",
    "通知已发送": "Notification sent",
    "文字与边框": "Text & borders",
    "后台订单表": "Admin order table",
    "联系与业务": "Contact & business",
    "普通管理员": "Standard admin",
    "分类已显示": "Category visible",
    "标签已删除": "Tag deleted",
    "标签已创建": "Tag created",
    "排序已保存": "Sort order saved",
    "会员专享券": "Member-only coupon",
    "金刚区": "Quick links",
    "金刚区导航": "Quick-link navigation",
    "全部SKU": "All SKUs",
    "与售价相同": "Same as sale price",
    "商品卡变体": "Product card variant",
    "分类已添加": "Category added",
    "视频已上传": "Video uploaded",
    "新标签名称": "New tag name",
    "分类已更新": "Category updated",
    "按状态筛选": "Filter by status",
    "超级管理员": "Super admin",
    "新品主视觉": "New arrivals hero",
    "今日新用户": "New users today",
    "请填写完整": "Please complete all fields",
    "中秋9.5折": "Mid-Autumn 5% off",
    "精选商品": "Featured product",
    "加载活动失败": "Failed to load campaign",
    "低库存SKU": "Low-stock SKUs",
    "更新状态失败": "Failed to update status",
    "请输入积分数": "Enter points",
    "客服支持说明": "Support instructions",
    "前台展示名称": "Storefront display name",
    "留空则不展示": "Leave blank to hide",
    "管理员已创建": "Admin created",
    "前往新品上市": "Go to new arrivals",
    "皮肤健康检查": "Theme health check",
    "限时特惠商品": "Limited-time deals",
    "统一活动库存": "Shared campaign stock",
    "自动确认天数": "Auto-confirm days",
    "活动名称必填": "Campaign name is required",
    "今日积分发放": "Points issued today",
    "昵称": "Nickname",
    "确认发布活动": "Publish campaign",
    "输入标签名称": "Enter tag name",
    "统一每人限购": "Per-user purchase limit",
    "暂无积分明细": "No points history",
    "更新标签失败": "Failed to update tag",
    "后台主题模式": "Admin theme mode",
    "密码至少6位": "Password must be at least 6 characters",
    "商品更新成功": "Product updated",
    "预警值已保存": "Alert threshold saved",
    "搜索活动名称": "Search campaign name",
    "如": "e.g.",
    "市场专员": "Sales associate",
    "已复制颜色值": "Color copied",
    "钻石会员": "Diamond member",
    "加载事件失败": "Failed to load events",
    "首页推荐展示": "Homepage featured",
    "输入商品名称": "Enter product name",
    "视频上传失败": "Video upload failed",
    "当前图标预览": "Current icon preview",
    "输入分类名称": "Enter category name",
    "刷新物流失败": "Failed to refresh tracking",
    "售后内部编号": "Return internal ID",
    "状态更新失败": "Failed to update status",
    "原因": "Reason",
    "主视觉": "Hero",
    "副标题": "Subtitle",
    "暂无导出任务": "No export jobs",
    "创建标签失败": "Failed to create tag",
    "例如": "e.g.",
    "大马通": "FlashCast",
    "管理员已删除": "Admin deleted",
    "商品创建成功": "Product created",
    "输入快递单号": "Enter tracking number",
    "备注": "Notes",
    "数码专享": "Electronics exclusive",
    "累计已支付订单": "Lifetime paid orders",
    "展示规则已保存": "Display rules saved",
    "新密码至少6位": "New password must be at least 6 characters",
    "数量必须为整数": "Quantity must be an integer",
    "已记录重放操作": "Replay logged",
    "物流轨迹已刷新": "Tracking refreshed",
    "已补记为已支付": "Marked as paid (manual)",
    "已保存皮肤配置": "Theme config saved",
    "优惠券创建成功": "Coupon created",
    "运费模板已创建": "Shipping template created",
    "打开日期与时间": "Open date & time",
    "个人信息已更新": "Profile updated",
    "盘点后实际库存": "Stock after count",
    "已设为默认皮肤": "Set as default theme",
    "精选状态已更新": "Featured status updated",
    "已创建对账草稿": "Reconciliation draft created",
    "优惠券更新成功": "Coupon updated",
    "下单奖励": "Order reward",
    "用户标签已更新": "User tags updated",
    "会员等级已创建": "Member tier created",
    "累计扣减": "Total deductions",
    "回滚": "Rollback",
    "返现规则已保存": "Cashback rules saved",
    "退款扣回": "Refund clawback",
    "请输入当前密码": "Enter current password",
    "导出任务已创建": "Export job created",
    "成本价": "Cost price",
    "运费模板已更新": "Shipping template updated",
    "加载展示规则失败": "Failed to load display rules",
    "草稿至少需要标题": "Draft requires a title",
    "加载库存统计失败": "Failed to load inventory stats",
    "调整原因": "Adjustment reason",
    "至少保留一条规格": "Keep at least one variant",
    "活动编号": "Campaign code",
    "来源单号": "Source reference",
    "加载商品信息失败": "Failed to load product",
    "至少配置一档满减": "Configure at least one spend tier",
    "商品编号": "Product code",
    "新品主视觉已保存": "New arrivals hero saved",
    "折扣比例": "Discount rate",
    "销售额": "Sales",
    "商品总额": "Product subtotal",
    "加载积分明细失败": "Failed to load points history",
    "基于当前皮肤复制": "Duplicate from current theme",
    "请输入优惠券编码": "Enter coupon code",
    "加载经营总览失败": "Failed to load overview",
    "对比": "Compare",
    "昨日": "yesterday",
    "上周期": "prior period",
    "请输入优惠券名称": "Enter coupon name",
    "皮肤名称不能为空": "Theme name cannot be empty",
    "暂无SKU库存数据": "No SKU stock data",
    "适用范围": "Applicable scope",
    "全场商品": "All products",
    "高亮标签": "Highlight tags",
    "活动角标": "Campaign badge",
    "加载SKU库存失败": "Failed to load SKU stock",
    "自动触发规则已保存": "Auto-trigger rules saved",
    "整页底色": "Page background",
    "列表背景": "List background",
    "优惠券编号": "Coupon code",
    "热销": "Hot",
    "推荐": "Recommended",
    "每批数量": "Batch size",
    "帮助中心配置已保存": "Help center saved",
    "新密码": "New password",
    "加载新品主视觉失败": "Failed to load new-arrivals hero",
    "无法加载该用户的角色": "Could not load roles for this user",
    "说明": "Description",
    "时间": "Time",
    "辅助信息": "Additional info",
    "密码": "Password",
    "排序保存失败": "Failed to save sort order",
    "秒杀活动": "Flash sale",
    "点击跳转链接": "Click-through link",
    "预警值": "Alert threshold",
    "非负整数": "non-negative integer",
    "帮助中心配置保存失败": "Failed to save help center",
    "保存自动触发规则失败": "Failed to save auto-trigger rules",
    "商品名": "Product name",
    "规格编码": "SKU code",
    "成功状态": "Success states",
    "完成": "Complete",
    "通过": "Approved",
    "请完成活动规则后预览": "Complete campaign rules to preview",
    "填写后优先使用此链接": "This link takes priority when set",
    "待处理": "Pending",
    "提醒": "Reminder",
    "库存预警": "Low-stock alert",
    "备案号": "ICP / filing number",
    "工商注册号": "Business registration",
    "最多保留": "Keep up to",
    "套皮肤": "themes",
    "标题": "Title",
    "正文": "Body",
    "表格主文字": "table text",
    "次按钮": "Secondary button",
    "标签底": "Tag background",
    "区块强调": "section accent",
    "卡片边框": "Card border",
    "表格线": "Table lines",
    "分割线": "Dividers",
    "卡片": "Card",
    "弹层": "Overlay",
    "输入框底色": "Input background",
    "删除": "Delete",
    "库存不足": "Insufficient stock",
    "取消订单": "Cancel order",
    "商品卡内标题与价格的对齐方式。": "Alignment of title and price on product cards.",
    "底部": "Footer",
    "关于我们": "About us",
    "订单页": "Order page",
    "都会展示": "shown on",
    "全站字体族": "Site-wide font family",
    "影响前台与后台文字渲染。": "Affects storefront and admin text rendering.",
    "商品卡外壳": "Product card shell",
    "商品图填充方式": "Product image fit",
    "裁切铺满或完整显示。": "Cover crop or fit entire image.",
    "正文色，用于标题、正文、表格主文字。": "Body text color for titles, copy, and tables.",
    "卡片与浮层的阴影强度，影响层次感。": "Shadow strength for cards and overlays.",
    "加载皮肤配置失败，已使用本地预设": "Failed to load theme — using local preset",
    "填写视频 URL，或点击右侧上传": "Enter video URL or upload on the right",
    "填写内部订单编号（见下方流水悬停提示）": "Enter internal order ID (see transaction tooltip below)",
    "图片 URL（可手动粘贴或点右侧上传）": "Image URL (paste or upload on the right)",
    "删除、失败、库存不足、取消订单": "Delete, failure, low stock, cancelled orders",
    "用户手机号或昵称（定向发送时）": "User phone or nickname (for targeted send)",
    "短时间低价促销，支持库存与限购": "Short-term sale with stock and purchase limits",
    "订单满额减免，可全场或定向": "Order discount — storewide or targeted",
    "面向会员展示的升级说明": "Upgrade description shown to members",
    "自定义标题（留空用默认）": "Custom title (blank = default)",
    "自定义正文（留空用默认）": "Custom body (blank = default)",
    "订单号或内部编号（可选）": "Order # or internal ID (optional)",
    "请输入新密码（至少6位）": "Enter new password (min. 6 characters)",
    "输入新密码（至少6位）": "Enter new password (min. 6 characters)",
    "新密码（至少6位）": "New password (min. 6 characters)",
    "密码 *（至少6位）": "Password * (min. 6 characters)",
    "胶囊": "Pill",
    "商品名称": "Product name",
    "如：标准版": "e.g. Standard",
    "精选商品 C": "Featured product C",
    "库存更新失败": "Failed to update inventory",
    "精选商品 A": "Featured product A",
    "搜索商品名称": "Search product name",
    "精选商品 B": "Featured product B",
    "下单奖励(旧)": "Order reward (legacy)",
    "累计扣减/回滚": "Total deductions / rollbacks",
    "请输入快递单号": "Enter tracking number",
    "请输入商品名称": "Enter product name",
    "退款扣回(旧)": "Refund clawback (legacy)",
    "请再次输入新密码": "Enter new password again",
    "系统角色不可删除": "System roles cannot be deleted",
    "适用范围：全场商品": "Scope: all products",
    "高亮标签、活动角标": "Highlight tags & campaign badges",
    "整页底色、列表背景": "Page background & list background",
    "热销/推荐每批数量": "Hot / recommended batch size",
    "说明、时间、辅助信息": "Captions, time & secondary info",
    "商品名 / 规格编码": "Product name / SKU code",
    "成功状态、完成、通过": "Success, completed, approved",
    "待处理、提醒、库存预警": "Pending, alerts, low-stock warnings",
    "最多保留 20 套皮肤": "Keep up to 20 themes",
    "卡片、弹层、输入框底色": "Card, overlay & input backgrounds",
    "标题、正文、表格主文字": "Titles, body & table text",
    "次按钮、标签底、区块强调": "Secondary buttons, tag bg & accents",
    "卡片边框、表格线、分割线": "Card borders, table lines & dividers",
    "商品价格、促销价格、优惠强调": "Price, sale price & discount emphasis",
    "底部、关于我们、订单页都会展示": "Shown in footer, About & order pages",
    "商品卡外壳：描边、无缝、悬浮、极简。": "Product card shell: outline, seamless, elevated, or minimal.",
    "全站字体族，影响前台与后台文字渲染。": "Site-wide font family for storefront and admin.",
    "商品图填充方式：裁切铺满或完整显示。": "Product image fit: cover crop or full image.",
    "跳转链接（如 /categories）": "Link target (e.g. /categories)",
    "搜索订单号 / 昵称 / 手机号...": "Search order # / nickname / phone...",
    "边框色，用于卡片边框、表格线、分割线。": "Border color for cards, tables & dividers.",
    "页面背景色，影响整页底色与列表区域背景。": "Page background color for page and list areas.",
    "商品图展示比例，影响列表与详情主图区域。": "Product image aspect ratio for list and detail.",
    "自动确认天数须为 1–365 之间的整数": "Auto-confirm days must be an integer from 1–365",
    "个人中心会员卡渐变风格，与首页预览一致。": "Profile membership card gradient — matches home preview.",
    "搜索订单号 / 联系人 / 手机号...": "Search order # / contact / phone...",
    "强调色用于高亮标签、活动角标、营销点缀。": "Accent color for tags, badges & marketing highlights.",
    "SST 税率须为 0–100 之间的数字": "SST rate must be a number from 0–100",
    "优惠券卡片视觉：票券、高级、促销、极简。": "Coupon card style: ticket, premium, promo, or minimal.",
    "首页顶部栏风格：简洁、高级、透明、深色。": "Home header style: clean, premium, transparent, or dark.",
    "例如：WhatsApp / 电话 / 邮箱": "e.g. WhatsApp / phone / email",
    "搜索评论内容 / 用户名 / 商品名...": "Search review / username / product...",
    "视频仅支持 MP4、WebM、MOV 格式": "Video: MP4, WebM, or MOV only",
    "成功色，用于完成、通过、库存充足等正向状态。": "Success color for positive states.",
    "商品卡布局变体：标准、高级、促销、紧凑横版。": "Product card layout: standard, premium, promo, or compact.",
    "Theme Studio 预览 Banner": "Theme Studio preview banner",
    "图标 URL（建议 128×128 正方形）": "Icon URL (128×128 square recommended)",
    "活动已有参与数据时删除将影响统计，确认删除？": "Delete campaign with participation data? Stats will be affected.",
    "首页 Banner 圆角、遮罩与促销强调风格。": "Home banner corners, overlay & promo emphasis.",
    "首页分类入口图标：圆形、柔和底、实心底、描边。": "Category icon style: circle, soft, solid, or outline.",
    "警告色，用于待处理、提醒、库存预警等注意状态。": "Warning color for attention states.",
    "主视觉图片（推荐 1200×1200，1:1）": "Hero image (1200×1200, 1:1 recommended)",
    "服务器未返回视频地址，请检查存储配置或稍后重试": "Server did not return video URL. Check storage or try again.",
    "首页区块编排风格：经典、杂志、促销等布局节奏。": "Home section layout: classic, magazine, promo, etc.",
    "如 shichang（英文标识，创建后不可改）": "e.g. shichang (slug, cannot change after create)",
    "每个条目必须包含 label 与 path 字段": "Each entry must have label and path",
    "卡片背景色，用于商品卡、弹层、输入框等浮层表面。": "Card background for cards, overlays & inputs.",
    "次文字色，用于说明、时间、辅助信息等弱层级文字。": "Secondary text for captions and metadata.",
    "辅色用于次按钮、标签底、区块强调等次要视觉层次。": "Secondary color for minor UI layers.",
    "后台主题：跟随前台皮肤，或固定为安全中性后台色。": "Admin theme: follow storefront or fixed neutral admin palette.",
    "删除标签后会同步移除用户身上的该标签，确定删除？": "Delete tag and remove it from all users?",
    "排序：数字越小越靠前（如 0 会排在 1 前面）": "Sort order: lower numbers appear first (0 before 1)",
    "累计已支付金额达此值即达标（与订单笔数为「或」）": "Lifetime paid amount threshold (OR with order count)",
    "例如 slug terms-of-service": "e.g. slug terms-of-service",
    "搜索订单号 / 描述 / 昵称 / 手机号...": "Search order # / description / nickname / phone...",
    "将自动跳转到 /categories 并选中该分类": "Will open /categories and select that category",
    "如：7×24 小时人工客服，下单 24 小时内必复": "e.g. 24/7 support, reply within 24h of order",
    "文件名,类型,状态,大小,创建时间,完成时间,操作": "File, type, status, size, created, completed, actions",
    "开启后，用户可在前台皮肤选择器中看到并切换此皮肤。": "When enabled, users can select this theme on the storefront.",
    "价格文字粗细与高级感（常规 / 加粗 / 高级）。": "Price typography weight (normal / bold / premium).",
    "当前有未保存修改，切换后将丢弃这些修改，确定继续吗？": "Unsaved changes will be lost. Continue?",
    "底部导航外观：简洁通栏、居中悬浮胶囊、半透明毛玻璃。": "Tab bar style: simple bar, floating pill, or frosted glass.",
    "累计已支付订单笔数达此值即达标（与消费金额为「或」）": "Lifetime order count threshold (OR with spend amount)",
    "价格色用于商品价格、促销价、优惠金额等商业信息强调。": "Price color for commercial emphasis.",
    "全局圆角基准，影响卡片、输入框、Banner 等组件。": "Global corner radius for cards, inputs, banners, etc.",
    "分享卡片图（OG Image，推荐 1200×630）": "Share image (OG, 1200×630 recommended)",
    "摘要 / 操作人 / 动作 / 对象编号 / 错误信息": "Summary / actor / action / object ID / error",
    "危险色，用于删除、失败、库存不足、取消订单等风险操作。": "Danger color for destructive or risky actions.",
    "上传后自动填入，或可填 URL / 路径 / Emoji": "Auto-filled after upload, or enter URL / path / emoji",
    "界面密度：舒适为默认间距，紧凑缩小卡片、列表与表格行高。": "UI density: comfortable (default) or compact spacing.",
    "如：每日 16:00 前付款当天发货，全马 2-5 天到达": "e.g. Ship same day if paid before 16:00, 2–5 days nationwide",
    "数字越大，同时达标多个等级时越优先；本页列表按此值升序排列": "Higher value wins when multiple tiers match; list sorted ascending",
    "Logo (推荐 256×256，上传后统一转 WEBP)": "Logo (256×256 recommended, converted to WEBP)",
    "删除后不可恢复。默认皮肤无法删除，需先指定其他皮肤为默认。": "Cannot be undone. Set another default before deleting the default theme.",
    "控制主按钮与次要按钮的圆角形态（胶囊 / 圆角 / 方角）。": "Button corner style: pill, rounded, or square.",
    "用英文逗号分隔, 例: shop,malaysia,gift": "Comma-separated, e.g. shop,malaysia,gift",
    "Favicon (推荐 32×32，上传后统一转 WEBP)": "Favicon (32×32 recommended, converted to WEBP)",
    "用于首页 hero / SEO description 兜底": "Fallback for home hero / SEO description",
    "补单接口需要 orders 表内部编号，可在支付流水订单列悬停查看": "Manual order needs internal orders ID — hover payment transaction row",
    "主色用于主按钮、导航选中、分类选中、后台菜单激活态等核心交互元素。": "Primary color for main buttons, active nav, and admin menu.",
    "短文案，可在购物车、Checkout、订单详情等转化关键节点透出，提升信任度": "Short trust copy on cart, checkout, and order pages",
    "填写 1–365 的整数；保存时会自动限制在范围内。仅对已有「发货时间」的订单生效。": "Integer 1–365; clamped on save. Only orders with ship time.",
    "搜索引擎抓取与社交分享时使用，未填写时回退到「站点名称 / 站点描述 / Logo」": "For SEO/social; falls back to site name / description / logo",
    "与内容管理中该页的 slug 一致，例如 slug 为 privacy-policy": "Must match content slug, e.g. privacy-policy",
    "含税反算：税额 = 应税含税商品金额 × 税率 ÷ (100 + 税率)。常见 6%。": "Tax included: tax = taxable × rate ÷ (100 + rate). Often 6%.",
    "铺满新品模块正方形容器（object-cover），与右侧商品 1:1 轮播图分层展示": "Cover-fill square new-arrivals module with 1:1 product carousel",
    "含货币与订单履约规则；自动确认以订单首次发货时间（管理端发货或手动改为已发货时写入）为起点。": "Currency & fulfillment rules; auto-confirm starts at first shipment time.",
    "用于首页「新品上市」运营氛围层；模块整体为 1:1 方形容器，主视觉与商品轮播图均为正方形展示。": "Home new-arrivals hero layer; 1:1 square visuals and carousel.",
    "开启并填写 Pixel ID 后，用户同意「广告 Cookie」才会加载 Meta Pixel。": "Meta Pixel loads only after ad cookies consent when Pixel ID is set.",
    "网站名称、Slogan、Logo / Favicon — 全站头部、底部、登录页、文档标题都会读取": "Site name, slogan, logo & favicon used across header, footer, login & title",
    "配置后前端仍会等待用户同意：拒绝分析/广告 Cookie 时不会加载对应第三方脚本，也不会发送事件。": "Third-party scripts load only after cookie consent.",
    "如：支持 Visa / Master / FPX，支付通道由 Stripe 提供，全程 SSL 加密": "e.g. Visa / Master / FPX via Stripe with SSL",
    "开启并填写 Measurement ID 后，用户同意「分析 Cookie」才会加载 gtag.js。": "gtag.js loads only after analytics cookies consent when ID is set.",
    "未登录首页底部页脚（品牌区、公司名称、版权等）会读取此处。政策类正文请在侧栏「内容管理」编辑对应页面，勿再使用外链。": "Guest home footer reads from here. Edit policies in Content, not external links.",
    "开启后新订单会按含税价拆分税额（仅对商品优惠后的商品金额计税，运费不计税），并在前台/后台展示。历史订单无税务快照则不显示税行。": "New orders show tax breakdown (products only, not shipping). Legacy orders without tax snapshot hide tax row.",
    "填写前台路由（一般为 /content/ + 内容管理里的 slug）。用户点击「隐私政策」「服务条款」等会进入站内页面展示你在内容管理里保存的正文。": "Storefront path, usually /content/ + slug from Content management.",
    "JSON 格式 [{label,path}]。配置后将完全覆盖默认页脚导航；不填则使用内置默认（关于我们 / 帮助中心 / 隐私 / 协议 / 退款 / 配送）": "JSON [{label,path}]. Overrides default footer nav if set.",
    "开启后，已发货订单超过下方天数仍未手动确认时，系统将自动变为「已完成」并结算积分与邀请返现（与买家点击确认收货一致）。服务端约每 15 分钟扫描一次，可用环境变量 AUTO_CONFIRM_RECEIVE_INTERVAL_MS 调整间隔。": "Shipped orders auto-complete after N days (same as buyer confirm). Scanned ~every 15 min; tune AUTO_CONFIRM_RECEIVE_INTERVAL_MS.",
    "无": "None",
    "编辑中": "Editing",
}

# Prefix / suffix patterns
PAST_PREFIX = {
    "付款": "Paid",
    "支付": "Paid",
    "发货": "Shipped",
    "完成": "Completed",
    "取消": "Cancelled",
    "启用": "Enabled",
    "禁用": "Disabled",
    "删除": "Deleted",
    "保存": "Saved",
    "创建": "Created",
    "更新": "Updated",
    "恢复": "Restored",
    "关闭": "Closed",
    "发送": "Sent",
    "绑定": "Linked",
    "过期": "Expired",
    "结束": "Ended",
    "隐藏": "Hidden",
    "使用": "Used",
    "停用": "Deactivated",
    "入账": "Posted",
    "冲正": "Reversed",
    "撤回": "Withdrawn",
    "提现": "Withdrawn",
    "精选": "Featured",
    "关联订单": "Order linked",
}

NOT_PREFIX = {
    "使用": "Unused",
    "分类": "Uncategorized",
    "开始": "Not started",
    "绑定": "Not linked",
    "读": "Unread",
    "命名分类": "Unnamed category",
    "命名商品": "Unnamed product",
    "命名皮肤": "Unnamed theme",
    "命名优惠券": "Unnamed coupon",
    "填写电话": "Phone not provided",
    "填写联系人": "Contact not provided",
    "登录首页": "Home (signed out)",
    "配置时回退到打包内置 logo": "Falls back to bundled logo when not configured",
}

NONE_PREFIX = {
    "数据": "No data",
    "商品": "No products",
    "用户": "No users",
    "活动": "No campaigns",
    "内容": "No content",
    "通知": "No notifications",
    "优惠券": "No coupons",
    "标题": "Untitled",
    "链接": "No link",
}

ING_SUFFIX = {
    "保存": "Saving",
    "删除": "Deleting",
    "上传": "Uploading",
    "提交": "Submitting",
    "发布": "Publishing",
    "创建": "Creating",
    "应用": "Applying",
    "新增": "Adding",
    "添加": "Adding",
    "解绑": "Unlinking",
    "加载": "Loading",
}


def _has_cjk(s: str) -> bool:
    return bool(CJK.search(s))


def _join(parts: list[str]) -> str:
    return " ".join(p for p in parts if p)


def _sub(zh: str) -> str:
    """Translate inner fragment (no pattern recursion)."""
    if zh in PHRASES:
        return PHRASES[zh]
    if zh in WORDS:
        return WORDS[zh]
    if len(zh) >= 2:
        parts: list[str] = []
        i = 0
        while i < len(zh):
            matched = False
            for length in range(min(8, len(zh) - i), 0, -1):
                chunk = zh[i : i + length]
                if chunk in WORDS:
                    parts.append(WORDS[chunk])
                    i += length
                    matched = True
                    break
            if not matched:
                return zh
        if parts:
            return _join(parts)
    return zh


def apply_pattern_rules(zh: str) -> str | None:
    """Regex-based templates for common admin copy."""
    rules: list[tuple[str, str]] = [
        (r"^请填写(.+)$", r"Please fill in \1"),
        (r"^请输入(.+)$", r"Please enter \1"),
        (r"^请选择(.+)$", r"Please select \1"),
        (r"^请上传(.+)$", r"Please upload \1"),
        (r"^请完成(.+)$", r"Please complete \1"),
        (r"^请再次(.+)$", r"Please \1 again"),
        (r"^搜索(.+)$", r"Search \1"),
        (r"^加载(.+)失败$", r"Failed to load \1"),
        (r"^保存(.+)失败$", r"Failed to save \1"),
        (r"^更新(.+)失败$", r"Failed to update \1"),
        (r"^创建(.+)失败$", r"Failed to create \1"),
        (r"^删除(.+)失败$", r"Failed to delete \1"),
        (r"^(.+)失败，请重试$", r"\1 failed, please try again"),
        (r"^(.+)失败$", r"\1 failed"),
        (r"^(.+)成功$", r"\1 succeeded"),
        (r"^确定(.+)[？?]$", r"Confirm \1?"),
        (r"^确认(.+)$", r"Confirm \1"),
        (r"^如[：:](.+)$", r"e.g. \1"),
        (r"^如 (.+)$", r"e.g. \1"),
        (r"^例如[：:](.+)$", r"e.g. \1"),
        (r"^(.+)必填$", r"\1 is required"),
        (r"^(.+)不能为空$", r"\1 cannot be empty"),
        (r"^(.+)（可选）$", r"\1 (optional)"),
        (r"^(.+)（必填）$", r"\1 (required)"),
        (r"^(.+)必须大于 0$", r"\1 must be greater than 0"),
        (r"^(.+)必须为非负整数$", r"\1 must be a non-negative integer"),
        (r"^(.+)必须 >= 0$", r"\1 must be >= 0"),
        (r"^(.+)必须晚于(.+)$", r"\1 must be later than \2"),
        (r"^(.+)不能超过(.+)$", r"\1 cannot exceed \2"),
        (r"^(.+)已(.+)$", r"\1 \2"),  # fallback — handled elsewhere
        (r"^添加 (.+)$", r"Add \1"),
        (r"^编辑 (.+)$", r"Edit \1"),
        (r"^输入(.+)$", r"Enter \1"),
        (r"^打开(.+)$", r"Open \1"),
        (r"^基于(.+)$", r"Based on \1"),
        (r"^与(.+)为「或」关系$", r"OR relationship with \1"),
        (r"^至少(.+)$", r"At least \1"),
        (r"^最多(.+)$", r"Up to \1"),
        (r"^开始/结束时间必填$", r"Start and end time are required"),
        (r"^两次密码不一致$", r"Passwords do not match"),
        (r"^密码至少(\d+)位$", r"Password must be at least \1 characters"),
        (r"^新密码至少(\d+)位$", r"New password must be at least \1 characters"),
        (r"^数量必须 > 0$", r"Quantity must be greater than 0"),
        (r"^数量必须为整数$", r"Quantity must be an integer"),
        (r"^配置 JSON 格式无效$", r"Invalid JSON configuration"),
        (r"^JSON 格式错误$", r"Invalid JSON"),
        (r"^footerNav 必须为数组$", r"footerNav must be an array"),
        (r"^0 = 无门槛$", r"0 = no minimum"),
        (r"^回收站为空$", r"Recycle bin is empty"),
        (r"^如何下单[？?]$", r"How to place an order?"),
        (r"^留空则不展示$", r"Leave blank to hide"),
        (r"^已是默认皮肤$", r"Already the default theme"),
        (r"^默认皮肤不可删除$", r"Default theme cannot be deleted"),
        (r"^配置完整，可发布$", r"Configuration complete — ready to publish"),
        (r"^已开始下载 CSV$", r"CSV download started"),
        (r"^订单文本已复制到剪贴板$", r"Order text copied to clipboard"),
        (r"^复制失败，请手动复制订单文本$", r"Copy failed — please copy the order text manually"),
        (r"^修改失败，请检查原密码$", r"Update failed — check your current password"),
        (r"^保存失败，请重试$", r"Save failed, please try again"),
        (r"^排序保存失败，请重试$", r"Failed to save sort order, please try again"),
        (r"^暂无轨迹，请点击刷新获取。$", r"No tracking yet. Tap refresh to fetch."),
        (r"^设置已保存，前端缓存已刷新$", r"Settings saved. Storefront cache refreshed."),
        (r"^模块开关已保存，前台刷新后生效$", r"Module toggles saved. Takes effect after storefront refresh."),
        (r"^图片已上传并保存到数据库$", r"Image uploaded and saved"),
        (r"^图标已上传，保存导航后生效$", r"Icon uploaded — save navigation to apply"),
        (r"^图片已上传，请记得点击底部「保存设置」$", r"Image uploaded — remember to click Save at the bottom"),
        (r"^已复制皮肤，请保存后生效$", r"Theme duplicated — save to apply"),
        (r"^已自动优化，可在右侧预览$", r"Auto-optimized — preview on the right"),
        (r"^已保存，并已应用到全站$", r"Saved and applied site-wide"),
        (r"^已从 JSON 导入到表单$", r"Imported from JSON into the form"),
        (r"^可粘贴 URL 或上传$", r"Paste a URL or upload"),
        (r"^上传或粘贴图片 URL$", r"Upload or paste image URL"),
        (r"^填写后优先使用此链接$", r"When set, this link takes priority"),
        (r"^用于生成 wa\.me 链接$", r"Used to build wa.me links"),
        (r"^GIF 上传后可能转为静态图$", r"GIF may be converted to a static image after upload"),
        (r"^当前仅支持同级分类内拖拽排序$", r"Drag-and-drop sorting is only supported within the same category level"),
        (r"^请选择单用户发送时，请填写用户ID$", r"When sending to one user, enter the user ID"),
        (r"^请选择至少一个适用分类$", r"Select at least one category"),
        (r"^请选择要跳转的分类$", r"Select a category to link to"),
        (r"^请填写订单号或内部订单编号$", r"Enter order number or internal reference"),
        (r"^请填写完整信息$", r"Please complete all fields"),
        (r"^请填写导航标题$", r"Enter navigation title"),
        (r"^请填写分类名称$", r"Enter category name"),
        (r"^秒杀活动必须选择商品$", r"Flash sale requires at least one product"),
        (r"^出库数量不能超过当前库存$", r"Outbound quantity cannot exceed current stock"),
        (r"^盘点后的库存必须 >= 0$", r"Stock count after adjustment must be >= 0"),
        (r"^满减金额不能大于门槛$", r"Discount cannot exceed the threshold"),
        (r"^满减门槛必须大于 0$", r"Spend threshold must be greater than 0"),
        (r"^满减金额必须大于 0$", r"Discount amount must be greater than 0"),
        (r"^结束时间必须晚于开始时间$", r"End time must be after start time"),
        (r"^图片大小不能超过 15MB$", r"Image size cannot exceed 15 MB"),
        (r"^视频大小不能超过 50MB$", r"Video size cannot exceed 50 MB"),
        (r"^仅支持 JPG、PNG、WebP 图片$", r"Only JPG, PNG, and WebP images are supported"),
        (r"^确定删除该优惠券？已领取记录将保留。$", r"Delete this coupon? Claim records will be kept."),
        (r"^全部检查通过，皮肤在前后台可读性良好。$", r"All checks passed — theme readability looks good on storefront and admin."),
        (r"^选择商品后加入购物车并提交订单。$", r"Add products to cart and place an order."),
        (r"^发货并填写运单号后可查看物流轨迹。$", r"Enter tracking after shipment to view logistics."),
        (r"^发货后自动确认收货$", r"Auto-confirm delivery after shipment"),
        (r"^控制首页各区块显示/隐藏$", r"Show or hide homepage sections"),
        (r"^对比昨日/上周期$", r"vs. yesterday / prior period"),
        (r"^对比上周同期$", r"vs. same period last week"),
        (r"^对比上月同期$", r"vs. same period last month"),
        (r"^同时达标多个等级时，数值越大越优先$", r"When multiple tiers match, the higher value wins"),
        (r"^与累计订单为「或」关系$", r"OR relationship with lifetime orders"),
        (r"^与累计消费为「或」关系$", r"OR relationship with lifetime spend"),
        (r"^输入积分数（正数增加，负数扣减）$", r"Enter points (positive to add, negative to deduct)"),
        (r"^🚚 运费: 包邮（不计税）$", r"🚚 Shipping: free (tax excluded)"),
        (r"^© 2026 大马通 版权所有$", r"© 2026 FlashCast. All rights reserved."),
        (r"^大马通 - 马来西亚优选商城$", r"FlashCast — Curated marketplace for Malaysia"),
        (r"^大马通精选商品 · 预览款$", r"FlashCast featured product · preview"),
        (r"^尊享品质，精选全球好物$", r"Premium quality, curated global picks"),
        (r"^每周精选，支持快速发货$", r"Weekly picks with fast shipping"),
        (r"^新品限时上新，错过再等一季$", r"Limited-time new arrivals — don’t miss out"),
        (r"^每天 9:00 - 22:00$", r"Daily 9:00 – 22:00"),
        (r"^周一至周日 09:00 - 22:00$", r"Mon–Sun 09:00 – 22:00"),
        (r"^例如：每天 9:00 - 22:00$", r"e.g. Daily 9:00 – 22:00"),
        (r"^例如：满100减10$", r"e.g. Spend 100, save 10"),
        (r"^如 10 表示减 10 元$", r"e.g. 10 means RM 10 off"),
        (r"^如 10 表示 9 折（减 10%）$", r"e.g. 10 means 10% off (pay 90%)"),
        (r"^批量折扣系数（如 0\.8）$", r"Bulk discount factor (e.g. 0.8)"),
        (r"^满 RM 50 可用$", r"Valid on orders over RM 50"),
        (r"^满 RM 100 可用$", r"Valid on orders over RM 100"),
        (r"^150 字以内，提升搜索点击率$", r"Within 150 characters — improves search CTR"),
        (r"^唯一编码，如 MANJIAN10$", r"Unique code, e.g. MANJIAN10"),
        (r"^适用区域（如：雪兰莪、吉隆坡）$", r"Regions (e.g. Selangor, Kuala Lumpur)"),
        (r"^WhatsApp 号码（仅数字）$", r"WhatsApp number (digits only)"),
        (r"^WhatsApp 完整链接（可选）$", r"Full WhatsApp link (optional)"),
        (r"^Meta Pixel 广告$", r"Meta Pixel ads"),
        (r"^Cookie 与埋点$", r"Cookies & tracking"),
        (r"^Cookie 同意与分析 / 广告埋点$", r"Cookie consent, analytics & ad tracking"),
        (r"^GA4 分析$", r"GA4 analytics"),
        (r"^SEO 与分享$", r"SEO & sharing"),
        (r"^SEO 标题$", r"SEO title"),
        (r"^SEO 描述$", r"SEO description"),
        (r"^SEO 关键词$", r"SEO keywords"),
        (r"^SST 税率（%）$", r"SST rate (%)"),
        (r"^展示 SST / 含税拆分$", r"Show SST / tax breakdown"),
        (r"^商品价格已含 SST，运费不计税。$", r"Product prices include SST; shipping is not taxed."),
        (r"^Footer 菜单 JSON$", r"Footer menu JSON"),
        (r"^页脚自定义导航 \(高级\)$", r"Custom footer navigation (advanced)"),
        (r"^服务条款 / 用户协议路径$", r"Terms of service path"),
        (r"^隐私政策路径$", r"Privacy policy path"),
        (r"^退款政策路径$", r"Refund policy path"),
        (r"^配送政策路径$", r"Shipping policy path"),
        (r"^政策内部页路径$", r"Internal policy page path"),
        (r"^购物 / 售后 / 支付说明$", r"Shopping / returns / payment info"),
        (r"^全站头部 / 浏览器标题尾缀$", r"Site header / browser title suffix"),
        (r"^备案号 / 工商注册号$", r"Registration / business license number"),
        (r"^微信应用 ID$", r"WeChat App ID"),
        (r"^微信 OpenID$", r"WeChat OpenID"),
        (r"^微信 UnionID$", r"WeChat UnionID"),
        (r"^微信绑定状态$", r"WeChat link status"),
        (r"^回调 / 事件$", r"Callbacks / events"),
        (r"^Slogan / 副标题$", r"Slogan / subtitle"),
        (r"^主视觉副标题$", r"Hero subtitle"),
        (r"^新品专区氛围图与文案$", r"New arrivals hero image & copy"),
        (r"^首页新品运营主视觉$", r"Homepage new-arrivals hero"),
        (r"^快捷入口图标与跳转$", r"Shortcut icons & links"),
        (r"^金刚区导航$", r"Quick-link navigation"),
        (r"^金刚区导航已创建$", r"Quick links created"),
        (r"^金刚区导航已更新$", r"Quick links updated"),
        (r"^保存金刚区导航失败$", r"Failed to save quick links"),
        (r"^Banner 标题$", r"Banner title"),
        (r"^添加 Banner$", r"Add banner"),
        (r"^编辑 Banner$", r"Edit banner"),
        (r"^Banner 已添加$", r"Banner added"),
        (r"^Banner 已更新$", r"Banner updated"),
        (r"^Banner 排序已更新$", r"Banner order updated"),
        (r"^加载 Banner 失败$", r"Failed to load banners"),
        (r"^折扣比例 \(%\)$", r"Discount (%)"),
        (r"^销售额 \(RM\)$", r"Sales (RM)"),
        (r"^优惠金额 \(RM\)$", r"Discount (RM)"),
        (r"^商品总额（含税）$", r"Product subtotal (incl. tax)"),
        (r"^商品合计（含税）$", r"Product total (incl. tax)"),
        (r"^订单号 / 交易号$", r"Order # / transaction ID"),
        (r"^搜索订单号 / 用户\.\.\.$", r"Search order # / user..."),
        (r"^搜索用户昵称 / 手机号\.\.\.$", r"Search nickname / phone..."),
        (r"^搜索邀请人 / 被邀请人\.\.\.$", r"Search referrer / invitee..."),
        (r"^搜索管理员手机号/昵称\.\.\.$", r"Search admin phone/nickname..."),
        (r"^搜索售后单号 / 订单号$", r"Search return # / order #"),
        (r"^搜索用户/优惠券\.\.\.$", r"Search user / coupon..."),
        (r"^搜索商品名称\.\.\.$", r"Search product name..."),
        (r"^搜索皮肤\.\.\.$", r"Search themes..."),
        (r"^搜索标题/编码$", r"Search title / code"),
        (r"^筛选商品\.\.\.$", r"Filter products..."),
        (r"^输入官方回复\.\.\.$", r"Enter official reply..."),
        (r"^简短商品描述\.\.\.$", r"Short product description..."),
        (r"^优惠券说明\.\.\.$", r"Coupon description..."),
        (r"^日（2 位）$", r"Day (2 digits)"),
        (r"^月（2 位）$", r"Month (2 digits)"),
        (r"^年（4 位）$", r"Year (4 digits)"),
        (r"^时（0–23，2 位）$", r"Hour (0–23, 2 digits)"),
        (r"^分（0–59，2 位）$", r"Minute (0–59, 2 digits)"),
        (r"^打开日期与时间$", r"Open date & time"),
        (r"^· 已关联$", r"· Linked"),
        (r"^· 已关联对象$", r"· Linked object"),
        (r"^· 已关联订单$", r"· Linked order"),
    ]
    for pattern, repl in rules:
        m = re.match(pattern, zh)
        if not m:
            continue
        groups = m.groups()
        if "\\1" in repl and groups:
            translated_groups = [_sub(g) for g in groups]
            if any(_has_cjk(t) for t in translated_groups):
                continue
            out = repl
            for i, tg in enumerate(translated_groups, start=1):
                out = out.replace(f"\\{i}", tg)
            if not _has_cjk(out):
                return out
        elif not groups:
            if not _has_cjk(repl):
                return repl
    return None


def translate_admin_zh(zh: str) -> str:
    zh = zh.strip()
    if not zh:
        return zh
    if zh in PHRASES:
        return PHRASES[zh]

    pat = apply_pattern_rules(zh)
    if pat:
        return pat

    m = re.match(r"^(.+)(中…|中\.\.\.|\.\.\.)$", zh)
    if m:
        base = m.group(1)
        if base in ING_SUFFIX:
            return f"{ING_SUFFIX[base]}..."
        if base in WORDS:
            return f"{WORDS[base]}..."

    if zh.startswith("已"):
        rest = zh[1:]
        if rest in PAST_PREFIX:
            return PAST_PREFIX[rest]
        if rest in WORDS:
            w = WORDS[rest]
            return w if w.endswith(("ed", "en", "t")) else f"{w}d" if w.endswith("e") else f"{w}ed"

    if zh.startswith("未"):
        rest = zh[1:]
        if rest in NOT_PREFIX:
            return NOT_PREFIX[rest]
        if rest in WORDS:
            return f"Not {WORDS[rest].lower()}"

    if zh.startswith("暂无"):
        rest = zh[2:]
        if rest in NONE_PREFIX:
            return NONE_PREFIX[rest]
        if rest in WORDS:
            return f"No {WORDS[rest].lower()}"

    if zh in WORDS:
        return WORDS[zh]

    # Compound: try joining known words (longest first)
    if len(zh) >= 2 and _has_cjk(zh):
        parts: list[str] = []
        i = 0
        while i < len(zh):
            matched = False
            for length in range(min(6, len(zh) - i), 0, -1):
                chunk = zh[i : i + length]
                if chunk in WORDS:
                    parts.append(WORDS[chunk])
                    i += length
                    matched = True
                    break
            if not matched:
                return zh
        if parts:
            return " ".join(parts)

    return zh


def polish_translation(zh: str, en: str) -> str:
    """Fix leftover CJK or broken hybrid strings."""
    if not _has_cjk(en) and " in progress" not in en and "Not " not in en[-6:]:
        return en
    better = translate_admin_zh(zh)
    return better if better != zh else en
